export const berkeleyMenuResponse = [
    {
      "location": "Berkeley",
      "today": {
        "contBreakfast": [
          {
            "hasInfo": true,
            "meal": "Contl. Bkfst.",
            "ingredients": [
              "Certified organic cage-free eggs"
            ],
            "allergens": [
              "Eggs"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "5.5 g",
              "vitaminA": "214.3 IU",
              "calories": "62 cal",
              "fat": "4.4 g",
              "cholesterol": "186 mg",
              "saturatedFat": "1.4 g",
              "servingSize": "1 Each",
              "vitaminC": "0.0 mg",
              "sugar": "0.3 g",
              "iron": "0.8 mg",
              "carbohydrates": "0.3 g",
              "fiber": "0.0 g"
            },
            "name": "Certified Organic, Cage-Free Hard-Boiled Eggs",
            "isVegetarian": true,
            "itemID": 3952458
          },
          {
            "hasInfo": true,
            "meal": "Contl. Bkfst.",
            "ingredients": [
              "Soy milk",
              "All-purpose flour",
              "Powdered sugar",
              "Baking powder",
              "Earth balance vegan butter spread",
              "Vanilla extract",
              "Baking soda",
              "Kosher salt",
              "Yellow cornmeal"
            ],
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "calories": "278 cal",
              "fat": "3.4 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.8 g",
              "servingSize": "1 Each",
              "vitaminC": "0.0 mg",
              "sugar": "10.8 g",
              "iron": "2.9 mg",
              "carbohydrates": "53.2 g",
              "fiber": "1.8 g",
              "protein": "7.5 g",
              "vitaminA": "151.9 IU"
            },
            "name": "Vegan Waffles",
            "isVegetarian": true,
            "itemID": 5908402
          },
          {
            "hasInfo": true,
            "meal": "Contl. Bkfst.",
            "ingredients": [
              "Tap water",
              "Waffle mix"
            ],
            "allergens": [
              "Dairy",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "0.0 g",
              "servingSize": "1 Serving",
              "vitaminC": "0.0 mg",
              "sugar": "5.1 g",
              "iron": "3.7 mg",
              "carbohydrates": "54.3 g",
              "fiber": "1.0 g",
              "protein": "5.1 g",
              "vitaminA": "0.0 IU",
              "calories": "276 cal",
              "fat": "3.1 g",
              "cholesterol": "0 mg"
            },
            "name": "Waffles",
            "isVegetarian": true,
            "itemID": 5910277
          },
          {
            "hasInfo": true,
            "meal": "Contl. Bkfst.",
            "ingredients": [
              "All-purpose flour",
              "Milk",
              "Superfine sugar",
              "Eggs",
              "Unsalted butter",
              "Clover honey",
              "Baking powder",
              "Poppy seeds",
              "Lemon extract",
              "Salt",
              "Pure vanilla extract"
            ],
            "allergens": [
              "Alcohol",
              "Dairy",
              "Eggs",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "5.8 g",
              "vitaminA": "348.7 IU",
              "calories": "327 cal",
              "fat": "10.4 g",
              "cholesterol": "70 mg",
              "saturatedFat": "6.0 g",
              "servingSize": "1 Each",
              "vitaminC": "0.1 mg",
              "sugar": "24.8 g",
              "iron": "2.1 mg",
              "carbohydrates": "52.0 g",
              "fiber": "1.0 g"
            },
            "name": "Lemon-Poppyseed Muffins",
            "isVegetarian": true,
            "itemID": 5358681
          },
          {
            "hasInfo": true,
            "meal": "Contl. Bkfst.",
            "ingredients": [
              "Tap water",
              "Whole-grain",
              "Steel-cut oats"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "carbohydrates": "17.8 g",
              "fiber": "3.1 g",
              "protein": "4.3 g",
              "vitaminA": "0.0 IU",
              "calories": "104 cal",
              "fat": "1.9 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.3 g",
              "servingSize": "7.088 Ounce",
              "vitaminC": "0.0 mg",
              "sugar": "0.0 g",
              "iron": "1.1 mg"
            },
            "name": "Whole-Grain Irish Oatmeal",
            "isVegetarian": true,
            "itemID": 5890196
          }
        ],
        "lunch": [
          {
            "ingredients": [
              "All-natural grass-fed ground beef",
              "Flour tortillas",
              "Onions",
              "Tomatoes",
              "Cheddar cheese",
              "Shredded lettuce",
              "Taco shell",
              "Extra virgin olive oil",
              "Dark chili powder",
              "Kosher salt",
              "Spanish paprika",
              "Ground black pepper",
              "Ground cumin",
              "Cayenne pepper"
            ],
            "allergens": [
              "Dairy",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "carbohydrates": "21.4 g",
              "fiber": "2.3 g",
              "protein": "21.1 g",
              "vitaminA": "415.1 IU",
              "calories": "396 cal",
              "fat": "25.5 g",
              "cholesterol": "74 mg",
              "saturatedFat": "10.7 g",
              "servingSize": "1 Taco",
              "vitaminC": "4.1 mg",
              "sugar": "2.1 g",
              "iron": "2.1 mg"
            },
            "name": "Ground Beef Tacos",
            "isVegetarian": false,
            "itemID": 5471783,
            "hasInfo": true,
            "meal": "Lunch"
          },
          {
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Chicken thighs",
              "Sub spice blend mexican fm"
            ],
            "allergens": [],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "0.1 mg",
              "sugar": "0.2 g",
              "iron": "4.1 mg",
              "carbohydrates": "0.2 g",
              "fiber": "0.0 g",
              "protein": "22.3 g",
              "vitaminA": "24.7 IU",
              "calories": "163 cal",
              "fat": "8.1 g",
              "cholesterol": "96 mg",
              "saturatedFat": "2.0 g",
              "servingSize": "1 Serving"
            },
            "name": "Chicken Thigh Carnitas",
            "isVegetarian": false,
            "itemID": 7950427
          },
          {
            "isVegetarian": true,
            "itemID": 399283,
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Low-sodium vegetable stock",
              "Black beans",
              "Onions",
              "Sun-dried tomatoes",
              "Extra virgin olive oil",
              "Chipotle peppers in adobo",
              "Garlic",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": [
              "Soy"
            ],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "3.4 mg",
              "sugar": "3.9 g",
              "iron": "2.7 mg",
              "carbohydrates": "21.9 g",
              "fiber": "12.0 g",
              "protein": "7.9 g",
              "vitaminA": "307.5 IU",
              "calories": "96 cal",
              "fat": "2.7 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.3 g",
              "servingSize": "3.76 Ounce"
            },
            "name": "Stewed Black Beans"
          },
          {
            "meal": "Lunch",
            "ingredients": [
              "Baby spinach",
              "Spanish onions",
              "Flour tortillas",
              "Shredded pepper jack cheese",
              "Medium tomato salsa",
              "Cilantro",
              "Extra virgin olive oil",
              "Lime juice",
              "Jalapeno peppers",
              "Garlic",
              "Kosher salt",
              "Garlic powder",
              "Ground black pepper",
              "Marjoram leaves",
              "Onion powder"
            ],
            "allergens": [
              "Dairy",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "15.3 mg",
              "sugar": "2.4 g",
              "iron": "2.4 mg",
              "carbohydrates": "21.8 g",
              "fiber": "2.9 g",
              "protein": "8.5 g",
              "vitaminA": "4181.9 IU",
              "calories": "204 cal",
              "fat": "9.7 g",
              "cholesterol": "16 mg",
              "saturatedFat": "4.0 g",
              "servingSize": "1 Each"
            },
            "name": "Spinach and Cheese Flauta",
            "isVegetarian": false,
            "itemID": 7908508,
            "hasInfo": true
          },
          {
            "ingredients": [
              "Low-sodium vegetable stock",
              "Plum tomatoes",
              "Corn",
              "Onions",
              "Dried celery",
              "Ground cori",
              "Er",
              "Kosher salt",
              "Garlic",
              "Canola oil",
              "Ground black pepper",
              "Dried thyme"
            ],
            "allergens": [
              "Soy"
            ],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "fat": "1.6 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.1 g",
              "servingSize": "6 Fluid Ounce",
              "vitaminC": "11.9 mg",
              "sugar": "4.5 g",
              "iron": "0.5 mg",
              "carbohydrates": "13.7 g",
              "fiber": "2.4 g",
              "protein": "2.7 g",
              "vitaminA": "1378.9 IU",
              "calories": "70 cal"
            },
            "name": "Roasted Corn and Tomato Soup",
            "isVegetarian": true,
            "itemID": 5676883,
            "hasInfo": true,
            "meal": "Lunch"
          },
          {
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Low-Sodium Chicken Stock",
              "Sub Matzo Ball",
              "Chicken Thighs",
              "Onions",
              "Carrots",
              "Dried Celery",
              "Fresh Dill",
              "Black Peppercorns",
              "Fresh Bay Leaves"
            ],
            "allergens": [
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "3.4 g",
              "servingSize": "6 Fluid Ounce",
              "vitaminC": "0.0 mg",
              "sugar": "0.7 g",
              "iron": "0.2 mg",
              "carbohydrates": "7.8 g",
              "fiber": "0.3 g",
              "protein": "2.7 g",
              "vitaminA": "199.7 IU",
              "calories": "98 cal",
              "fat": "6.3 g",
              "cholesterol": "61 mg"
            },
            "name": "Matzo Ball Soup",
            "isVegetarian": false,
            "itemID": 3617831
          },
          {
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "3.6 g",
              "vitaminA": "541.3 IU",
              "calories": "131 cal",
              "fat": "7.6 g",
              "cholesterol": "0 mg",
              "saturatedFat": "1.0 g",
              "servingSize": "3 Ounce",
              "vitaminC": "16.2 mg",
              "sugar": "2.0 g",
              "iron": "1.1 mg",
              "carbohydrates": "12.0 g",
              "fiber": "3.2 g"
            },
            "name": "Fresh Green Garbanzo Salad with Apples, Avocado-Lime Vinaigrette, and Crispy Chickpeas",
            "isVegetarian": true,
            "itemID": 3362345,
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Green garbanzo beans",
              "Avocado-lime vinaigrette",
              "Apples",
              "Crispy chickpeas",
              "Cilantro",
              "Carrots",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": []
          },
          {
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Wild baby arugula",
              "Cannellini beans",
              "Feta cheese",
              "Tomatoes",
              "Cucumber",
              "Kalamata olives",
              "Red onions",
              "Extra virgin olive oil",
              "Pepperoncini peppers",
              "Lemon juice",
              "Red wine vinegar",
              "Parsley",
              "Mint",
              "Garlic",
              "Curly parsley",
              "Oregano",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": [
              "Dairy"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "3.3 g",
              "vitaminA": "1113.7 IU",
              "calories": "72 cal",
              "fat": "5.0 g",
              "cholesterol": "7 mg",
              "saturatedFat": "1.6 g",
              "servingSize": "3 Ounce",
              "vitaminC": "8.7 mg",
              "sugar": "1.5 g",
              "iron": "0.9 mg",
              "carbohydrates": "4.6 g",
              "fiber": "1.4 g"
            },
            "name": "Greek Salad with Arugula",
            "isVegetarian": false,
            "itemID": 3871561
          },
          {
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Quinoa",
              "Low-sodium black beans",
              "Bell peppers",
              "Corn kernels",
              "Scallions",
              "Extra virgin olive oil",
              "Lime juice",
              "Cilantro",
              "Kosher salt",
              "Ground cumin"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "calories": "105 cal",
              "fat": "3.8 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.4 g",
              "servingSize": "3 Ounce",
              "vitaminC": "19.6 mg",
              "sugar": "1.5 g",
              "iron": "0.9 mg",
              "carbohydrates": "15.8 g",
              "fiber": "1.8 g",
              "protein": "3.0 g",
              "vitaminA": "136.7 IU"
            },
            "name": "Southwest Quinoa Salad",
            "isVegetarian": true,
            "itemID": 5348503
          },
          {
            "isVegetarian": false,
            "itemID": 6784067,
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Pea Protein",
              "Canola Oil",
              "Refined Coconut Oil",
              "Water",
              "Yeast Extract",
              "Maltodextrin",
              "Natural Flavors",
              "Gum Arabic",
              "Sunflower Oil",
              "Salt",
              "Succinic Acid",
              "Acetic Acid",
              "Non-Gmo Modified Food Starch",
              "Cellulose From Bamboo",
              "Methylcellulose",
              "Potato Starch",
              "Beet Juice Extract",
              "Ascorbi",
              "Wheat Hamburger Bun"
            ],
            "allergens": [
              "Nuts",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "calories": "438 cal",
              "fat": "23.9 g",
              "cholesterol": "0 mg",
              "saturatedFat": "8.5 g",
              "servingSize": "1 Each",
              "vitaminC": "53.9 mg",
              "sugar": "3.0 g",
              "iron": "1.4 mg",
              "carbohydrates": "33.9 g",
              "fiber": "5.0 g",
              "protein": "25.9 g",
              "vitaminA": "0.0 IU"
            },
            "name": "Beyond Meat Burger"
          },
          {
            "nutrition": {
              "calories": "397 cal",
              "fat": "21.5 g",
              "cholesterol": "85 mg",
              "saturatedFat": "9.1 g",
              "servingSize": "1 Sandwich",
              "vitaminC": "8.1 mg",
              "sugar": "3.5 g",
              "iron": "2.2 mg",
              "carbohydrates": "29.2 g",
              "fiber": "2.1 g",
              "protein": "20.8 g",
              "vitaminA": "2219.9 IU"
            },
            "name": "Grass-Fed Hand Shaped Burger",
            "isVegetarian": false,
            "itemID": 5263541,
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Grass-Fed Ground Beef",
              "Mushroom Duxelles",
              "Kosher Salt",
              "Black Pepper",
              "Brioche Roll",
              "Better Burger Leaf Lettuce",
              "Tomato",
              "Vegan Mayo",
              "Lemon Juice",
              "Dill Pickle Relish",
              "Garlic Powder",
              "Paprika",
              "Less than  2% Silicon Dioxide",
              "Onion Powder"
            ],
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false
          },
          {
            "isVegetarian": false,
            "itemID": 5416409,
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Grass-Fed Ground Beef",
              "Mushroom Duxelles",
              "Kosher Salt",
              "Black Pepper",
              "Brioche Roll",
              "Better Burger Leaf Lettuce",
              "Tomatoes",
              "White Cheddar Cheese",
              "Vegan Mayo",
              "Lemon Juice",
              "Dill Pickle Relish",
              "Garlic Powder",
              "Paprika",
              "Less than  2% Silicon Dioxide",
              "Onion Powder"
            ],
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "12.1 g",
              "servingSize": "1 Sandwich",
              "vitaminC": "8.1 mg",
              "sugar": "3.5 g",
              "iron": "2.2 mg",
              "carbohydrates": "29.7 g",
              "fiber": "2.1 g",
              "protein": "24.4 g",
              "vitaminA": "2370.1 IU",
              "calories": "452 cal",
              "fat": "26.5 g",
              "cholesterol": "103 mg"
            },
            "name": "Grass-Fed Hand-Shaped Cheeseburger"
          },
          {
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "11.0 g",
              "vitaminA": "1748.9 IU",
              "calories": "239 cal",
              "fat": "3.5 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.5 g",
              "servingSize": "1 Each",
              "vitaminC": "6.0 mg",
              "sugar": "5.0 g",
              "iron": "3.2 mg",
              "carbohydrates": "43.0 g",
              "fiber": "5.0 g"
            },
            "name": "Vegan Sweet Potato and Black Bean Burger",
            "isVegetarian": true,
            "itemID": 5926612,
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Vegan Black Bean",
              "Sweet Potato Burger",
              "Wheat Hamburger Bun"
            ],
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten"
            ]
          },
          {
            "ingredients": [
              "Enriched Wheat Flour",
              "Shortening",
              "Yeast",
              "Salt",
              "Sugar",
              "Garlic",
              "Canola Oil with Citric Acid",
              "Plum Tomatoes",
              "Mozzarella Cheese",
              "Italian Basil",
              "Grated Parmesan Cheese",
              "Extra Virgin Olive Oil",
              "Kosher Salt",
              "Ground Black Pepper"
            ],
            "allergens": [
              "Dairy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "10.4 mg",
              "sugar": "1.8 g",
              "iron": "1.5 mg",
              "carbohydrates": "50.3 g",
              "fiber": "15.6 g",
              "protein": "24.6 g",
              "vitaminA": "1162.3 IU",
              "calories": "515 cal",
              "fat": "26.6 g",
              "cholesterol": "31 mg",
              "saturatedFat": "7.9 g",
              "servingSize": "1 Slice"
            },
            "name": "Margherita Pizza",
            "isVegetarian": false,
            "itemID": 4124835,
            "hasInfo": true,
            "meal": "Lunch"
          },
          {
            "nutrition": {
              "saturatedFat": "7.8 g",
              "servingSize": "1 Slice",
              "vitaminC": "10.1 mg",
              "sugar": "1.8 g",
              "iron": "1.6 mg",
              "carbohydrates": "48.1 g",
              "fiber": "15.0 g",
              "protein": "18.8 g",
              "vitaminA": "306.1 IU",
              "calories": "435 cal",
              "fat": "18.0 g",
              "cholesterol": "42 mg"
            },
            "name": "Cheese Pizza",
            "isVegetarian": true,
            "itemID": 4903686,
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Enriched Wheat Flour",
              "Shortening",
              "Yeast",
              "Salt",
              "Sugar",
              "Garlic",
              "Canola Oil with Citric Acid",
              "Sauce Pizza FM",
              "Shredded Mozzarella Cheese",
              "Ovolini Mozzarella Ball",
              "Pecorino Romano Cheese"
            ],
            "allergens": [
              "Dairy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false
          },
          {
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Enriched wheat flour",
              "Shortening",
              "Yeast",
              "Salt",
              "Sugar",
              "Garlic",
              "Canola oil with citric acid",
              "Plum tomatoes",
              "Mozzarella cheese",
              "Italian basil",
              "Grated parmesan cheese",
              "Extra virgin olive oil",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": [
              "Dairy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "iron": "1.5 mg",
              "carbohydrates": "50.3 g",
              "fiber": "15.6 g",
              "protein": "24.6 g",
              "vitaminA": "1162.3 IU",
              "calories": "515 cal",
              "fat": "26.6 g",
              "cholesterol": "31 mg",
              "saturatedFat": "7.9 g",
              "servingSize": "1 Slice",
              "vitaminC": "10.4 mg",
              "sugar": "1.8 g"
            },
            "name": "Chef's Choice Pizza",
            "isVegetarian": false,
            "itemID": 5716323
          },
          {
            "meal": "Lunch",
            "ingredients": [
              "Tomatoes",
              "Suntan bell pepper",
              "Basmati rice",
              "Medium tomato salsa",
              "Onions",
              "Canola oil",
              "Garlic puree",
              "Ground cori",
              "Er",
              "Ground black pepper"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "fat": "1.8 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.1 g",
              "servingSize": "4 Ounce",
              "vitaminC": "26.9 mg",
              "sugar": "2.9 g",
              "iron": "0.1 mg",
              "carbohydrates": "25.5 g",
              "fiber": "1.4 g",
              "protein": "3.1 g",
              "vitaminA": "223.4 IU",
              "calories": "127 cal"
            },
            "name": "Mexican Rice",
            "isVegetarian": true,
            "itemID": 5076605,
            "hasInfo": true
          },
          {
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "79.6 mg",
              "sugar": "2.8 g",
              "iron": "1.1 mg",
              "carbohydrates": "7.2 g",
              "fiber": "2.8 g",
              "protein": "2.4 g",
              "vitaminA": "1444.8 IU",
              "calories": "74 cal",
              "fat": "4.9 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.7 g",
              "servingSize": "4 Ounce"
            },
            "name": "Roasted Brussels Sprouts with Squash and Red Peppers",
            "isVegetarian": true,
            "itemID": 6072636,
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Brussels sprouts",
              "Green squash",
              "Red bell peppers",
              "Extra virgin olive oil",
              "Italian parsley",
              "Red wine vinegar",
              "Kosher salt",
              "Basil",
              "Ground black pepper"
            ],
            "allergens": []
          },
          {
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "0.0 g",
              "servingSize": "4 Ounce",
              "vitaminC": "0.0 mg",
              "sugar": "0.0 g",
              "iron": "0.6 mg",
              "carbohydrates": "49.4 g",
              "fiber": "1.5 g",
              "protein": "4.6 g",
              "vitaminA": "0.0 IU",
              "calories": "231 cal",
              "fat": "1.5 g",
              "cholesterol": "0 mg"
            },
            "name": "Steamed Brown Rice",
            "isVegetarian": true,
            "itemID": 4166320,
            "hasInfo": true,
            "meal": "Lunch",
            "ingredients": [
              "Long-grain brown rice",
              "Tap water"
            ],
            "allergens": []
          },
          {
            "ingredients": [
              "Pastry flour",
              "Unsalted butter",
              "Confectioners sugar",
              "Macadamia nuts",
              "Shredded sweetened coconut",
              "Passion fruit puree",
              "Pure vanilla extract",
              "Salt"
            ],
            "allergens": [
              "Alcohol",
              "Nuts",
              "Dairy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "0.1 mg",
              "sugar": "6.2 g",
              "iron": "0.5 mg",
              "carbohydrates": "23.0 g",
              "fiber": "1.3 g",
              "protein": "2.3 g",
              "vitaminA": "419.6 IU",
              "calories": "256 cal",
              "fat": "18.0 g",
              "cholesterol": "36 mg",
              "saturatedFat": "10.0 g",
              "servingSize": "1 Cookie"
            },
            "name": "Passion Fruit Coconut Macadamia Shortbread",
            "isVegetarian": false,
            "itemID": 5480238,
            "hasInfo": true,
            "meal": "Lunch"
          },
          {
            "ingredients": [
              "All-purpose flour",
              "Unsalted butter",
              "Semisweet chocolate chip",
              "Light brown sugar",
              "Superfine sugar",
              "Eggs",
              "Pure vanilla extract",
              "Salt",
              "Cream of tartar",
              "Baking soda"
            ],
            "allergens": [
              "Alcohol",
              "Dairy",
              "Eggs",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "fat": "12.7 g",
              "cholesterol": "47 mg",
              "saturatedFat": "7.7 g",
              "servingSize": "1 Serving",
              "vitaminC": "0.0 mg",
              "sugar": "23.4 g",
              "iron": "1.5 mg",
              "carbohydrates": "39.4 g",
              "fiber": "1.2 g",
              "protein": "3.2 g",
              "vitaminA": "298.6 IU",
              "calories": "278 cal"
            },
            "name": "Chocolate Chip Blondies",
            "isVegetarian": true,
            "itemID": 4118782,
            "hasInfo": true,
            "meal": "Lunch"
          }
        ],
        "brunch": [],
        "dinner": [
          {
            "isVegetarian": false,
            "itemID": 5463072,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Tomatoes",
              "All-natural grass-fed ground beef",
              "Ground pork",
              "Low-sodium chicken stock",
              "Burgundy wine",
              "Carrots",
              "Dried celery",
              "Onions",
              "Extra virgin olive oil",
              "Tomato paste",
              "Kosher salt",
              "Ground black pepper",
              "Dried bay leaves"
            ],
            "allergens": [
              "Alcohol",
              "Pork",
              "Soy"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "6.6 g",
              "servingSize": "4 Fluid Ounce",
              "vitaminC": "8.3 mg",
              "sugar": "2.5 g",
              "iron": "1.2 mg",
              "carbohydrates": "5.3 g",
              "fiber": "1.1 g",
              "protein": "14.0 g",
              "vitaminA": "1796.2 IU",
              "calories": "264 cal",
              "fat": "19.8 g",
              "cholesterol": "56 mg"
            },
            "name": "Bolognese Sauce"
          },
          {
            "nutrition": {
              "fat": "5.9 g",
              "cholesterol": "19 mg",
              "saturatedFat": "3.5 g",
              "servingSize": "6 Ounce",
              "vitaminC": "5.7 mg",
              "sugar": "4.0 g",
              "iron": "5.5 mg",
              "carbohydrates": "49.8 g",
              "fiber": "6.9 g",
              "protein": "19.9 g",
              "vitaminA": "490.7 IU",
              "calories": "342 cal"
            },
            "name": "Red Lentil Pasta with Vodka Sauce",
            "isVegetarian": false,
            "itemID": 5935930,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Red lentil penne pasta",
              "Crushed tomatoes",
              "Heavy whipping cream",
              "Shallots",
              "Vodka",
              "Unsalted butter",
              "Italian basil",
              "Grated parmesan cheese",
              "Garlic",
              "Red pepper flakes"
            ],
            "allergens": [
              "Alcohol",
              "Dairy"
            ],
            "isVegan": false,
            "isGlutenFree": false
          },
          {
            "ingredients": [
              "Orecchiette pasta",
              "Broccoli raab",
              "Vegan soy sausage crumble",
              "Spanish onion",
              "Tomato paste",
              "Italian parsley",
              "Extra virgin olive oil",
              "Oregano",
              "Chives",
              "Italian basil",
              "Kosher salt",
              "Garlic",
              "Ground black pepper",
              "Red pepper flakes"
            ],
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "15.0 mg",
              "sugar": "3.0 g",
              "iron": "3.9 mg",
              "carbohydrates": "36.0 g",
              "fiber": "5.7 g",
              "protein": "11.8 g",
              "vitaminA": "1677.1 IU",
              "calories": "239 cal",
              "fat": "6.1 g",
              "cholesterol": "7 mg",
              "saturatedFat": "0.7 g",
              "servingSize": "6.88 Ounce"
            },
            "name": "Orecchiette with Vegan Soy Sausage and Broccoli Rabe",
            "isVegetarian": true,
            "itemID": 487517,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "nutrition": {
              "vitaminC": "11.9 mg",
              "sugar": "4.5 g",
              "iron": "0.5 mg",
              "carbohydrates": "13.7 g",
              "fiber": "2.4 g",
              "protein": "2.7 g",
              "vitaminA": "1378.9 IU",
              "calories": "70 cal",
              "fat": "1.6 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.1 g",
              "servingSize": "6 Fluid Ounce"
            },
            "name": "Roasted Corn and Tomato Soup",
            "isVegetarian": true,
            "itemID": 5676883,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Low-sodium vegetable stock",
              "Plum tomatoes",
              "Corn",
              "Onions",
              "Dried celery",
              "Ground cori",
              "Er",
              "Kosher salt",
              "Garlic",
              "Canola oil",
              "Ground black pepper",
              "Dried thyme"
            ],
            "allergens": [
              "Soy"
            ],
            "isVegan": true,
            "isGlutenFree": false
          },
          {
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Low-Sodium Chicken Stock",
              "Sub Matzo Ball",
              "Chicken Thighs",
              "Onions",
              "Carrots",
              "Dried Celery",
              "Fresh Dill",
              "Black Peppercorns",
              "Fresh Bay Leaves"
            ],
            "allergens": [
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "3.4 g",
              "servingSize": "6 Fluid Ounce",
              "vitaminC": "0.0 mg",
              "sugar": "0.7 g",
              "iron": "0.2 mg",
              "carbohydrates": "7.8 g",
              "fiber": "0.3 g",
              "protein": "2.7 g",
              "vitaminA": "199.7 IU",
              "calories": "98 cal",
              "fat": "6.3 g",
              "cholesterol": "61 mg"
            },
            "name": "Matzo Ball Soup",
            "isVegetarian": false,
            "itemID": 3617831
          },
          {
            "isVegetarian": true,
            "itemID": 3362345,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Green garbanzo beans",
              "Avocado-lime vinaigrette",
              "Apples",
              "Crispy chickpeas",
              "Cilantro",
              "Carrots",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "calories": "131 cal",
              "fat": "7.6 g",
              "cholesterol": "0 mg",
              "saturatedFat": "1.0 g",
              "servingSize": "3 Ounce",
              "vitaminC": "16.2 mg",
              "sugar": "2.0 g",
              "iron": "1.1 mg",
              "carbohydrates": "12.0 g",
              "fiber": "3.2 g",
              "protein": "3.6 g",
              "vitaminA": "541.3 IU"
            },
            "name": "Fresh Green Garbanzo Salad with Apples, Avocado-Lime Vinaigrette, and Crispy Chickpeas"
          },
          {
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Wild baby arugula",
              "Cannellini beans",
              "Feta cheese",
              "Tomatoes",
              "Cucumber",
              "Kalamata olives",
              "Red onions",
              "Extra virgin olive oil",
              "Pepperoncini peppers",
              "Lemon juice",
              "Red wine vinegar",
              "Parsley",
              "Mint",
              "Garlic",
              "Curly parsley",
              "Oregano",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": [
              "Dairy"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "iron": "0.9 mg",
              "carbohydrates": "4.6 g",
              "fiber": "1.4 g",
              "protein": "3.3 g",
              "vitaminA": "1113.7 IU",
              "calories": "72 cal",
              "fat": "5.0 g",
              "cholesterol": "7 mg",
              "saturatedFat": "1.6 g",
              "servingSize": "3 Ounce",
              "vitaminC": "8.7 mg",
              "sugar": "1.5 g"
            },
            "name": "Greek Salad with Arugula",
            "isVegetarian": false,
            "itemID": 3871561
          },
          {
            "ingredients": [
              "Quinoa",
              "Low-sodium black beans",
              "Bell peppers",
              "Corn kernels",
              "Scallions",
              "Extra virgin olive oil",
              "Lime juice",
              "Cilantro",
              "Kosher salt",
              "Ground cumin"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "0.4 g",
              "servingSize": "3 Ounce",
              "vitaminC": "19.6 mg",
              "sugar": "1.5 g",
              "iron": "0.9 mg",
              "carbohydrates": "15.8 g",
              "fiber": "1.8 g",
              "protein": "3.0 g",
              "vitaminA": "136.7 IU",
              "calories": "105 cal",
              "fat": "3.8 g",
              "cholesterol": "0 mg"
            },
            "name": "Southwest Quinoa Salad",
            "isVegetarian": true,
            "itemID": 5348503,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "nutrition": {
              "saturatedFat": "8.5 g",
              "servingSize": "1 Each",
              "vitaminC": "53.9 mg",
              "sugar": "3.0 g",
              "iron": "1.4 mg",
              "carbohydrates": "33.9 g",
              "fiber": "5.0 g",
              "protein": "25.9 g",
              "vitaminA": "0.0 IU",
              "calories": "438 cal",
              "fat": "23.9 g",
              "cholesterol": "0 mg"
            },
            "name": "Beyond Meat Burger",
            "isVegetarian": false,
            "itemID": 6784067,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Pea Protein",
              "Canola Oil",
              "Refined Coconut Oil",
              "Water",
              "Yeast Extract",
              "Maltodextrin",
              "Natural Flavors",
              "Gum Arabic",
              "Sunflower Oil",
              "Salt",
              "Succinic Acid",
              "Acetic Acid",
              "Non-Gmo Modified Food Starch",
              "Cellulose From Bamboo",
              "Methylcellulose",
              "Potato Starch",
              "Beet Juice Extract",
              "Ascorbi",
              "Wheat Hamburger Bun"
            ],
            "allergens": [
              "Nuts",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false
          },
          {
            "ingredients": [
              "Grass-Fed Ground Beef",
              "Mushroom Duxelles",
              "Kosher Salt",
              "Black Pepper",
              "Brioche Roll",
              "Better Burger Leaf Lettuce",
              "Tomato",
              "Vegan Mayo",
              "Lemon Juice",
              "Dill Pickle Relish",
              "Garlic Powder",
              "Paprika",
              "Less than  2% Silicon Dioxide",
              "Onion Powder"
            ],
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "carbohydrates": "29.2 g",
              "fiber": "2.1 g",
              "protein": "20.8 g",
              "vitaminA": "2219.9 IU",
              "calories": "397 cal",
              "fat": "21.5 g",
              "cholesterol": "85 mg",
              "saturatedFat": "9.1 g",
              "servingSize": "1 Sandwich",
              "vitaminC": "8.1 mg",
              "sugar": "3.5 g",
              "iron": "2.2 mg"
            },
            "name": "Grass-Fed Hand Shaped Burger",
            "isVegetarian": false,
            "itemID": 5263541,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Grass-Fed Ground Beef",
              "Mushroom Duxelles",
              "Kosher Salt",
              "Black Pepper",
              "Brioche Roll",
              "Better Burger Leaf Lettuce",
              "Tomatoes",
              "White Cheddar Cheese",
              "Vegan Mayo",
              "Lemon Juice",
              "Dill Pickle Relish",
              "Garlic Powder",
              "Paprika",
              "Less than  2% Silicon Dioxide",
              "Onion Powder"
            ],
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "calories": "452 cal",
              "fat": "26.5 g",
              "cholesterol": "103 mg",
              "saturatedFat": "12.1 g",
              "servingSize": "1 Sandwich",
              "vitaminC": "8.1 mg",
              "sugar": "3.5 g",
              "iron": "2.2 mg",
              "carbohydrates": "29.7 g",
              "fiber": "2.1 g",
              "protein": "24.4 g",
              "vitaminA": "2370.1 IU"
            },
            "name": "Grass-Fed Hand-Shaped Cheeseburger",
            "isVegetarian": false,
            "itemID": 5416409
          },
          {
            "ingredients": [
              "Vegan Black Bean",
              "Sweet Potato Burger",
              "Wheat Hamburger Bun"
            ],
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "11.0 g",
              "vitaminA": "1748.9 IU",
              "calories": "239 cal",
              "fat": "3.5 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.5 g",
              "servingSize": "1 Each",
              "vitaminC": "6.0 mg",
              "sugar": "5.0 g",
              "iron": "3.2 mg",
              "carbohydrates": "43.0 g",
              "fiber": "5.0 g"
            },
            "name": "Vegan Sweet Potato and Black Bean Burger",
            "isVegetarian": true,
            "itemID": 5926612,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "ingredients": [
              "Enriched Wheat Flour",
              "Shortening",
              "Yeast",
              "Salt",
              "Sugar",
              "Garlic",
              "Canola Oil with Citric Acid",
              "Plum Tomatoes",
              "Mozzarella Cheese",
              "Italian Basil",
              "Grated Parmesan Cheese",
              "Extra Virgin Olive Oil",
              "Kosher Salt",
              "Ground Black Pepper"
            ],
            "allergens": [
              "Dairy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "calories": "515 cal",
              "fat": "26.6 g",
              "cholesterol": "31 mg",
              "saturatedFat": "7.9 g",
              "servingSize": "1 Slice",
              "vitaminC": "10.4 mg",
              "sugar": "1.8 g",
              "iron": "1.5 mg",
              "carbohydrates": "50.3 g",
              "fiber": "15.6 g",
              "protein": "24.6 g",
              "vitaminA": "1162.3 IU"
            },
            "name": "Margherita Pizza",
            "isVegetarian": false,
            "itemID": 4124835,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "ingredients": [
              "Sub chicken thighs thai fm",
              "Thai peanut sauce",
              "Enriched wheat flour",
              "Shortening",
              "Yeast",
              "Salt",
              "Sugar",
              "Garlic",
              "Canola oil with citric acid",
              "Sub pickled carrot fm",
              "Sub cabbage pickled fm",
              "Red onions",
              "White vinegar",
              "Tarragon vinegar",
              "Bay leaves",
              "Mustard seeds",
              "Scallions",
              "Extra virgin olive oil",
              "Garlic oil"
            ],
            "allergens": [
              "Alcohol",
              "Peanut",
              "Fish/Seafood",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "8.6 mg",
              "sugar": "13.7 g",
              "iron": "0.5 mg",
              "carbohydrates": "28.2 g",
              "fiber": "3.1 g",
              "protein": "4.0 g",
              "vitaminA": "736.3 IU",
              "calories": "203 cal",
              "fat": "7.6 g",
              "cholesterol": "0 mg",
              "saturatedFat": "1.0 g",
              "servingSize": "1 Slice"
            },
            "name": "Thai Chicken Pizza",
            "isVegetarian": false,
            "itemID": 2977318,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "nutrition": {
              "carbohydrates": "50.3 g",
              "fiber": "15.6 g",
              "protein": "24.6 g",
              "vitaminA": "1162.3 IU",
              "calories": "515 cal",
              "fat": "26.6 g",
              "cholesterol": "31 mg",
              "saturatedFat": "7.9 g",
              "servingSize": "1 Slice",
              "vitaminC": "10.4 mg",
              "sugar": "1.8 g",
              "iron": "1.5 mg"
            },
            "name": "Chef's Choice Pizza",
            "isVegetarian": false,
            "itemID": 5716323,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Enriched wheat flour",
              "Shortening",
              "Yeast",
              "Salt",
              "Sugar",
              "Garlic",
              "Canola oil with citric acid",
              "Plum tomatoes",
              "Mozzarella cheese",
              "Italian basil",
              "Grated parmesan cheese",
              "Extra virgin olive oil",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": [
              "Dairy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false
          },
          {
            "nutrition": {
              "saturatedFat": "0.0 g",
              "servingSize": "6 Ounce",
              "vitaminC": "0.0 mg",
              "sugar": "2.4 g",
              "iron": "0.0 mg",
              "carbohydrates": "51.0 g",
              "fiber": "2.4 g",
              "protein": "8.5 g",
              "vitaminA": "0.0 IU",
              "calories": "242 cal",
              "fat": "1.2 g",
              "cholesterol": "0 mg"
            },
            "name": "Pasta Cellentani Cooked 6 Oz",
            "isVegetarian": false,
            "itemID": 5169605,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Water",
              "Kosher salt",
              "Cellentani pasta"
            ],
            "allergens": [
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false
          },
          {
            "meal": "Dinner",
            "ingredients": [
              "Broccoli florets",
              "Extra virgin olive oil",
              "Garlic",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "0.8 g",
              "servingSize": "4 Ounce",
              "vitaminC": "95.6 mg",
              "sugar": "1.8 g",
              "iron": "0.8 mg",
              "carbohydrates": "7.4 g",
              "fiber": "2.8 g",
              "protein": "3.1 g",
              "vitaminA": "665.6 IU",
              "calories": "84 cal",
              "fat": "5.7 g",
              "cholesterol": "0 mg"
            },
            "name": "Sauteed Broccoli with Garlic",
            "isVegetarian": true,
            "itemID": 6087687,
            "hasInfo": true
          },
          {
            "ingredients": [
              "Long-Grain Brown Rice",
              "Tap Water"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "0.0 mg",
              "sugar": "0.0 g",
              "iron": "0.6 mg",
              "carbohydrates": "49.4 g",
              "fiber": "1.5 g",
              "protein": "4.6 g",
              "vitaminA": "0.0 IU",
              "calories": "231 cal",
              "fat": "1.5 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.0 g",
              "servingSize": "4 Ounce"
            },
            "name": "Steamed Brown Rice",
            "isVegetarian": true,
            "itemID": 4166320,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "ingredients": [
              "Certified Organic Cage-Free Eggs",
              "Gochujang Sauce",
              "Sub Pickled Daikon FM",
              "Kimchi",
              "Prep Bok Choy Baby Cut 1/2 in",
              "Scallions",
              "Carrots",
              "Sub Sauce Sesame Soy FM",
              "Sub Cucumber Pickled Cucumber FM"
            ],
            "allergens": [
              "Alcohol",
              "Eggs",
              "Fish/Seafood",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "6.8 mg",
              "sugar": "5.2 g",
              "iron": "1.2 mg",
              "carbohydrates": "8.2 g",
              "fiber": "1.0 g",
              "protein": "8.0 g",
              "vitaminA": "1923.6 IU",
              "calories": "146 cal",
              "fat": "9.1 g",
              "cholesterol": "239 mg",
              "saturatedFat": "2.1 g",
              "servingSize": "4 Ounce"
            },
            "name": "Bipimbap Bar",
            "isVegetarian": false,
            "itemID": 7970933,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "isVegetarian": false,
            "itemID": 3873170,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Tofu",
              "Extra Virgin Olive Oil",
              "WATER",
              "SOYBEANS",
              "SALT",
              "SUGAR",
              "ALCOHOL",
              "VINEGAR",
              "LACTIC ACID",
              "Kosher Salt",
              "Ground Black Pepper"
            ],
            "allergens": [
              "Soy"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "10.9 g",
              "vitaminA": "0.0 IU",
              "calories": "140 cal",
              "fat": "9.4 g",
              "cholesterol": "0 mg",
              "saturatedFat": "1.5 g",
              "servingSize": "1 Serving",
              "vitaminC": "0.0 mg",
              "sugar": "0.0 g",
              "iron": "1.7 mg",
              "carbohydrates": "1.8 g",
              "fiber": "4.9 g"
            },
            "name": "Roasted Soy Tofu"
          },
          {
            "ingredients": [
              "Sub Marinade Beef Bulgogi FM",
              "Beef Chuck Roll Bnls Raw Grass Fed"
            ],
            "allergens": [
              "Alcohol",
              "Soy"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "calories": "192 cal",
              "fat": "0.1 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.0 g",
              "servingSize": "5 Ounce",
              "vitaminC": "6.0 mg",
              "sugar": "40.2 g",
              "iron": "0.3 mg",
              "carbohydrates": "46.7 g",
              "fiber": "1.3 g",
              "protein": "1.3 g",
              "vitaminA": "15.5 IU"
            },
            "name": "Beef Bulgogi",
            "isVegetarian": false,
            "itemID": 4550315,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "ingredients": [
              "Superfine sugar",
              "Carrots",
              "All-purpose flour",
              "Egg whites",
              "Whole-wheat flour",
              "Milk",
              "Almonds",
              "Raisins",
              "Canola oil",
              "Roasted pistachios",
              "Baking soda",
              "Baking powder",
              "Pure vanilla extract",
              "Ground cinnamon",
              "Pumpkin puree",
              "Ground cardamom",
              "Salt"
            ],
            "allergens": [
              "Alcohol",
              "Nuts",
              "Dairy",
              "Eggs",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "1.2 mg",
              "sugar": "23.1 g",
              "iron": "1.5 mg",
              "carbohydrates": "40.0 g",
              "fiber": "2.7 g",
              "protein": "5.1 g",
              "vitaminA": "2443.0 IU",
              "calories": "244 cal",
              "fat": "7.6 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.7 g",
              "servingSize": "1 Each"
            },
            "name": "Indian Spice Carrot Cupcakes",
            "isVegetarian": true,
            "itemID": 5327197,
            "hasInfo": true,
            "meal": "Dinner"
          }
        ],
        "hotBreakfast": []
      },
      "tomorrow": {
        "brunch": [
          {
            "ingredients": [
              "Soy milk",
              "All-purpose flour",
              "Powdered sugar",
              "Baking powder",
              "Earth balance vegan butter spread",
              "Vanilla extract",
              "Baking soda",
              "Kosher salt",
              "Yellow cornmeal"
            ],
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "iron": "2.9 mg",
              "carbohydrates": "53.2 g",
              "fiber": "1.8 g",
              "protein": "7.5 g",
              "vitaminA": "151.9 IU",
              "calories": "278 cal",
              "fat": "3.4 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.8 g",
              "servingSize": "1 Each",
              "vitaminC": "0.0 mg",
              "sugar": "10.8 g"
            },
            "name": "Vegan Waffles",
            "isVegetarian": true,
            "itemID": 5908402,
            "hasInfo": true,
            "meal": "Brunch"
          },
          {
            "ingredients": [
              "Tap water",
              "Waffle mix"
            ],
            "allergens": [
              "Dairy",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminA": "0.0 IU",
              "calories": "276 cal",
              "fat": "3.1 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.0 g",
              "servingSize": "1 Serving",
              "vitaminC": "0.0 mg",
              "sugar": "5.1 g",
              "iron": "3.7 mg",
              "carbohydrates": "54.3 g",
              "fiber": "1.0 g",
              "protein": "5.1 g"
            },
            "name": "Waffles",
            "isVegetarian": true,
            "itemID": 5910277,
            "hasInfo": true,
            "meal": "Brunch"
          },
          {
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "4.3 g",
              "servingSize": "4 Ounce",
              "vitaminC": "0.0 mg",
              "sugar": "0.0 g",
              "iron": "1.8 mg",
              "carbohydrates": "0.0 g",
              "fiber": "0.0 g",
              "protein": "14.6 g",
              "vitaminA": "512.3 IU",
              "calories": "184 cal",
              "fat": "12.6 g",
              "cholesterol": "414 mg"
            },
            "name": "Cage-Free Scrambled Eggs",
            "isVegetarian": true,
            "itemID": 5902936,
            "hasInfo": true,
            "meal": "Brunch",
            "ingredients": [
              "Cage-free liquid eggs",
              "Clarified butter"
            ],
            "allergens": [
              "Dairy",
              "Eggs"
            ]
          },
          {
            "name": "Egg Shakshuka",
            "isVegetarian": true,
            "itemID": 6015960,
            "hasInfo": true,
            "meal": "Brunch",
            "ingredients": [
              "Spanish onions",
              "Tomato puree",
              "Certified organic cage-free eggs",
              "Rainbow chard",
              "Celery",
              "Green bell pepper",
              "Tap water",
              "Extra virgin olive oil",
              "Garlic",
              "Italian parsley",
              "Dark chili powder",
              "Ground cori",
              "Er",
              "Ground cumin"
            ],
            "allergens": [
              "Eggs"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "15.9 mg",
              "sugar": "3.1 g",
              "iron": "0.9 mg",
              "carbohydrates": "6.9 g",
              "fiber": "2.1 g",
              "protein": "4.1 g",
              "vitaminA": "1083.8 IU",
              "calories": "86 cal",
              "fat": "4.9 g",
              "cholesterol": "89 mg",
              "saturatedFat": "1.1 g",
              "servingSize": "4 Ounce"
            }
          },
          {
            "name": "Chefs Choice Whole Wheat Penne Pasta",
            "isVegetarian": false,
            "itemID": 5415656,
            "hasInfo": true,
            "meal": "Brunch",
            "ingredients": [
              "Whole wheat penne pasta",
              "Placeholder"
            ],
            "allergens": [
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "0.0 mg",
              "sugar": "2.5 g",
              "iron": "2.3 mg",
              "carbohydrates": "51.7 g",
              "fiber": "7.6 g",
              "protein": "8.8 g",
              "vitaminA": "0.0 IU",
              "calories": "252 cal",
              "fat": "1.9 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.0 g",
              "servingSize": "5 Ounce"
            }
          },
          {
            "ingredients": [
              "Sweet potatoes",
              "Canola oil",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "sugar": "4.6 g",
              "iron": "0.7 mg",
              "carbohydrates": "22.1 g",
              "fiber": "3.3 g",
              "protein": "1.7 g",
              "vitaminA": "15568.1 IU",
              "calories": "123 cal",
              "fat": "3.4 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.3 g",
              "servingSize": "4 Ounce",
              "vitaminC": "2.6 mg"
            },
            "name": "Sweet Potato Home Fries",
            "isVegetarian": true,
            "itemID": 5587822,
            "hasInfo": true,
            "meal": "Brunch"
          },
          {
            "ingredients": [
              "Fresh market vegetable"
            ],
            "allergens": [],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "0.0 mg",
              "sugar": "0.0 g",
              "iron": "0.0 mg",
              "carbohydrates": "0.0 g",
              "fiber": "0.0 g",
              "protein": "0.0 g",
              "vitaminA": "0.0 IU",
              "calories": "0 cal",
              "fat": "0.0 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.0 g",
              "servingSize": "4 Ounce"
            },
            "name": "Chefs Choice Vegetable",
            "isVegetarian": false,
            "itemID": 1023285,
            "hasInfo": true,
            "meal": "Brunch"
          },
          {
            "nutrition": {
              "vitaminC": "0.1 mg",
              "sugar": "12.9 g",
              "iron": "1.1 mg",
              "carbohydrates": "25.1 g",
              "fiber": "0.8 g",
              "protein": "3.4 g",
              "vitaminA": "22.7 IU",
              "calories": "225 cal",
              "fat": "12.4 g",
              "cholesterol": "18 mg",
              "saturatedFat": "4.7 g",
              "servingSize": "1 Cookie"
            },
            "name": "Honey Walnut Cookies",
            "isVegetarian": true,
            "itemID": 5311049,
            "hasInfo": true,
            "meal": "Brunch",
            "ingredients": [
              "All-purpose flour",
              "All-purpose shortening",
              "Light brown sugar",
              "Superfine sugar",
              "Walnuts",
              "Eggs",
              "Clover honey",
              "Salt",
              "Pure vanilla extract",
              "Baking soda",
              "Cream of tartar"
            ],
            "allergens": [
              "Alcohol",
              "Nuts",
              "Eggs",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false
          },
          {
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "2.6 mg",
              "sugar": "34.8 g",
              "iron": "1.3 mg",
              "carbohydrates": "51.8 g",
              "fiber": "1.1 g",
              "protein": "4.5 g",
              "vitaminA": "186.3 IU",
              "calories": "351 cal",
              "fat": "14.3 g",
              "cholesterol": "56 mg",
              "saturatedFat": "7.6 g",
              "servingSize": "32 Serving"
            },
            "name": "Lemon Coconut Oat Bars",
            "isVegetarian": true,
            "itemID": 4200887,
            "hasInfo": true,
            "meal": "Brunch",
            "ingredients": [
              "Lemon filling",
              "Bread flour",
              "Superfine sugar",
              "Shredded coconut",
              "Unsalted butter",
              "All-purpose shortening",
              "Rolled oats",
              "Eggs",
              "Salt"
            ],
            "allergens": [
              "Dairy",
              "Eggs",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false
          },
          {
            "ingredients": [
              "Plain greek yogurt",
              "Oats",
              "Raisins",
              "Coconut",
              "Almonds",
              "Soybean oil",
              "Light brown sugar",
              "Maple syrup",
              "Salt",
              "Craisins",
              "Local honey",
              "Sliced strawberries",
              "Shredded sweetened coconut"
            ],
            "allergens": [
              "Nuts",
              "Dairy"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "19.0 g",
              "vitaminA": "0.1 IU",
              "calories": "240 cal",
              "fat": "4.9 g",
              "cholesterol": "5 mg",
              "saturatedFat": "1.3 g",
              "servingSize": "5.5 Ounce",
              "vitaminC": "2.5 mg",
              "sugar": "32.9 g",
              "iron": "0.6 mg",
              "carbohydrates": "40.2 g",
              "fiber": "2.3 g"
            },
            "name": "Greek Yogurt Bar with Housemade Granola",
            "isVegetarian": true,
            "itemID": 5592712,
            "hasInfo": true,
            "meal": "Brunch"
          },
          {
            "hasInfo": true,
            "meal": "Brunch",
            "ingredients": [
              "Soy milk",
              "All-purpose flour",
              "Granulated sugar",
              "Cornstarch",
              "Earth balance vegan butter spread",
              "Baking powder",
              "Vanilla extract",
              "Ground cinnamon"
            ],
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "carbohydrates": "24.0 g",
              "fiber": "0.7 g",
              "protein": "3.0 g",
              "vitaminA": "56.9 IU",
              "calories": "132 cal",
              "fat": "2.4 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.7 g",
              "servingSize": "1 Each",
              "vitaminC": "0.0 mg",
              "sugar": "4.2 g",
              "iron": "1.2 mg"
            },
            "name": "Vegan Apple Cinnamon Pancakes",
            "isVegetarian": true,
            "itemID": 4103673
          },
          {
            "ingredients": [
              "Tap water",
              "Whole-grain",
              "Steel-cut oats"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "calories": "104 cal",
              "fat": "1.9 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.3 g",
              "servingSize": "7.088 Ounce",
              "vitaminC": "0.0 mg",
              "sugar": "0.0 g",
              "iron": "1.1 mg",
              "carbohydrates": "17.8 g",
              "fiber": "3.1 g",
              "protein": "4.3 g",
              "vitaminA": "0.0 IU"
            },
            "name": "Whole-Grain Irish Oatmeal",
            "isVegetarian": true,
            "itemID": 5890196,
            "hasInfo": true,
            "meal": "Brunch"
          },
          {
            "ingredients": [
              "Chicken",
              "Water",
              "Salt",
              "Red pepper",
              "Sage",
              "Sugar",
              "Black pepper"
            ],
            "allergens": [],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "1.0 g",
              "servingSize": "1 Each",
              "vitaminC": "0.0 mg",
              "sugar": "0.0 g",
              "iron": "0.0 mg",
              "carbohydrates": "2.0 g",
              "fiber": "0.0 g",
              "protein": "9.1 g",
              "vitaminA": "0.0 IU",
              "calories": "81 cal",
              "fat": "4.6 g",
              "cholesterol": "41 mg"
            },
            "name": "New Haven Savory Chicken Breakfast Sausage Patties with Sage",
            "isVegetarian": false,
            "itemID": 6572486,
            "hasInfo": true,
            "meal": "Brunch"
          }
        ],
        "dinner": [
          {
            "ingredients": [
              "Eggplant",
              "Red bell peppers",
              "Yellow squash",
              "Zucchini",
              "Fontina cheese",
              "Spinach",
              "Vegan roasted garlic mayonnaise",
              "Olive oil",
              "Canola blend",
              "Pizza bianca",
              "Italian basil",
              "Ground black pepper"
            ],
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "8.3 g",
              "servingSize": "1 Sandwich",
              "vitaminC": "96.2 mg",
              "sugar": "5.3 g",
              "iron": "1.7 mg",
              "carbohydrates": "13.2 g",
              "fiber": "5.4 g",
              "protein": "11.4 g",
              "vitaminA": "4613.0 IU",
              "calories": "354 cal",
              "fat": "29.5 g",
              "cholesterol": "37 mg"
            },
            "name": "Roasted  Vegetable and Fontina Cheese Panini",
            "isVegetarian": true,
            "itemID": 4432327,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "All-natural chicken breast",
              "Egg wash",
              "Breadcrumbs",
              "Tomato sauce",
              "Mozzarella cheese",
              "All-purpose flour"
            ],
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "3.9 g",
              "servingSize": "1 Serving",
              "vitaminC": "4.5 mg",
              "sugar": "3.7 g",
              "iron": "2.9 mg",
              "carbohydrates": "32.8 g",
              "fiber": "1.6 g",
              "protein": "40.5 g",
              "vitaminA": "256.5 IU",
              "calories": "412 cal",
              "fat": "11.0 g",
              "cholesterol": "185 mg"
            },
            "name": "Parmesan Breaded Chicken",
            "isVegetarian": false,
            "itemID": 3252122
          },
          {
            "isVegetarian": false,
            "itemID": 6784067,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Pea protein",
              "Canola oil",
              "Refined coconut oil",
              "Water",
              "Yeast extract",
              "Maltodextrin",
              "Natural flavors",
              "Gum arabic",
              "Sunflower oil",
              "Salt",
              "Succinic acid",
              "Acetic acid",
              "Non-gmo modified food starch",
              "Cellulose from bamboo",
              "Methylcellulose",
              "Potato starch",
              "Beet juice extract",
              "Ascorbi",
              "Wheat hamburger bun"
            ],
            "allergens": [
              "Nuts",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "iron": "1.4 mg",
              "carbohydrates": "33.9 g",
              "fiber": "5.0 g",
              "protein": "25.9 g",
              "vitaminA": "0.0 IU",
              "calories": "438 cal",
              "fat": "23.9 g",
              "cholesterol": "0 mg",
              "saturatedFat": "8.5 g",
              "servingSize": "1 Each",
              "vitaminC": "53.9 mg",
              "sugar": "3.0 g"
            },
            "name": "Beyond Meat Burger"
          },
          {
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Grass-fed ground beef",
              "Mushroom duxelles",
              "Kosher salt",
              "Black pepper",
              "Brioche roll",
              "Better burger leaf lettuce",
              "Tomato",
              "Vegan mayo",
              "Lemon juice",
              "Dill pickle relish",
              "Garlic powder",
              "Paprika"
            ],
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "sugar": "3.5 g",
              "iron": "2.2 mg",
              "carbohydrates": "29.2 g",
              "fiber": "2.1 g",
              "protein": "20.8 g",
              "vitaminA": "2219.9 IU",
              "calories": "397 cal",
              "fat": "21.5 g",
              "cholesterol": "85 mg",
              "saturatedFat": "9.1 g",
              "servingSize": "1 Sandwich",
              "vitaminC": "8.1 mg"
            },
            "name": "Grass-Fed Hand Shaped Burger",
            "isVegetarian": false,
            "itemID": 5263541
          },
          {
            "isVegetarian": false,
            "itemID": 5416409,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Grass-fed ground beef",
              "Mushroom duxelles",
              "Kosher salt",
              "Black pepper",
              "Brioche roll",
              "Better burger leaf lettuce",
              "Tomatoes",
              "White cheddar cheese",
              "Vegan mayo",
              "Lemon juice",
              "Dill pickle relish",
              "Garlic powder",
              "Paprika"
            ],
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "calories": "452 cal",
              "fat": "26.5 g",
              "cholesterol": "103 mg",
              "saturatedFat": "12.1 g",
              "servingSize": "1 Sandwich",
              "vitaminC": "8.1 mg",
              "sugar": "3.5 g",
              "iron": "2.2 mg",
              "carbohydrates": "29.7 g",
              "fiber": "2.1 g",
              "protein": "24.4 g",
              "vitaminA": "2370.1 IU"
            },
            "name": "Grass-Fed Hand-Shaped Cheeseburger"
          },
          {
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Vegan black bean",
              "Sweet potato burger",
              "Wheat hamburger bun"
            ],
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "11.0 g",
              "vitaminA": "1748.9 IU",
              "calories": "239 cal",
              "fat": "3.5 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.5 g",
              "servingSize": "1 Each",
              "vitaminC": "6.0 mg",
              "sugar": "5.0 g",
              "iron": "3.2 mg",
              "carbohydrates": "43.0 g",
              "fiber": "5.0 g"
            },
            "name": "Vegan Sweet Potato and Black Bean Burger",
            "isVegetarian": true,
            "itemID": 5926612
          },
          {
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Enriched wheat flour",
              "Shortening",
              "Yeast",
              "Salt",
              "Sugar",
              "Garlic",
              "Canola oil with citric acid",
              "Plum tomatoes",
              "Mozzarella cheese",
              "Italian basil",
              "Grated parmesan cheese",
              "Extra virgin olive oil",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": [
              "Dairy",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "24.6 g",
              "vitaminA": "1162.3 IU",
              "calories": "515 cal",
              "fat": "26.6 g",
              "cholesterol": "31 mg",
              "saturatedFat": "7.9 g",
              "servingSize": "1 Slice",
              "vitaminC": "10.4 mg",
              "sugar": "1.8 g",
              "iron": "1.5 mg",
              "carbohydrates": "50.3 g",
              "fiber": "15.6 g"
            },
            "name": "Margherita Pizza",
            "isVegetarian": false,
            "itemID": 4124835
          },
          {
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "10.5 g",
              "servingSize": "1 Slice",
              "vitaminC": "5.8 mg",
              "sugar": "1.8 g",
              "iron": "2.0 mg",
              "carbohydrates": "48.1 g",
              "fiber": "15.0 g",
              "protein": "23.7 g",
              "vitaminA": "411.9 IU",
              "calories": "504 cal",
              "fat": "24.5 g",
              "cholesterol": "58 mg"
            },
            "name": "Pepperoni Pizza",
            "isVegetarian": false,
            "itemID": 4917071,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Enriched wheat flour",
              "Shortening",
              "Yeast",
              "Salt",
              "Sugar",
              "Garlic",
              "Canola oil with citric acid",
              "Sauce pizza fm",
              "Shredded mozzarella cheese",
              "Pepperoni",
              "Pecorino romano cheese"
            ],
            "allergens": [
              "Dairy",
              "Pork",
              "Wheat",
              "Gluten"
            ]
          },
          {
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "calories": "515 cal",
              "fat": "26.6 g",
              "cholesterol": "31 mg",
              "saturatedFat": "7.9 g",
              "servingSize": "1 Slice",
              "vitaminC": "10.4 mg",
              "sugar": "1.8 g",
              "iron": "1.5 mg",
              "carbohydrates": "50.3 g",
              "fiber": "15.6 g",
              "protein": "24.6 g",
              "vitaminA": "1162.3 IU"
            },
            "name": "Chef's Choice Pizza",
            "isVegetarian": false,
            "itemID": 5716323,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Enriched wheat flour",
              "Shortening",
              "Yeast",
              "Salt",
              "Sugar",
              "Garlic",
              "Canola oil with citric acid",
              "Plum tomatoes",
              "Mozzarella cheese",
              "Italian basil",
              "Grated parmesan cheese",
              "Extra virgin olive oil",
              "Kosher salt",
              "Ground black pepper"
            ],
            "allergens": [
              "Dairy",
              "Wheat",
              "Gluten"
            ]
          },
          {
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Green swiss chard",
              "Cannellini beans",
              "Tomatoes",
              "Extra virgin olive oil",
              "Kosher salt",
              "Garlic",
              "Red pepper flakes"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "protein": "6.9 g",
              "vitaminA": "9508.9 IU",
              "calories": "134 cal",
              "fat": "5.0 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.7 g",
              "servingSize": "6 Ounce",
              "vitaminC": "51.6 mg",
              "sugar": "2.6 g",
              "iron": "3.7 mg",
              "carbohydrates": "17.7 g",
              "fiber": "5.9 g"
            },
            "name": "White Bean Stew with Swiss Chard and Tomatoes",
            "isVegetarian": true,
            "itemID": 873075
          },
          {
            "isVegetarian": false,
            "itemID": 1023285,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Fresh market vegetable"
            ],
            "allergens": [],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "saturatedFat": "0.0 g",
              "servingSize": "4 Ounce",
              "vitaminC": "0.0 mg",
              "sugar": "0.0 g",
              "iron": "0.0 mg",
              "carbohydrates": "0.0 g",
              "fiber": "0.0 g",
              "protein": "0.0 g",
              "vitaminA": "0.0 IU",
              "calories": "0 cal",
              "fat": "0.0 g",
              "cholesterol": "0 mg"
            },
            "name": "Chefs Choice Vegetable"
          },
          {
            "ingredients": [
              "Quinoa"
            ],
            "allergens": [],
            "isVegan": true,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "0.0 mg",
              "sugar": "1.8 g",
              "iron": "1.1 mg",
              "carbohydrates": "19.9 g",
              "fiber": "1.8 g",
              "protein": "3.6 g",
              "vitaminA": "0.0 IU",
              "calories": "102 cal",
              "fat": "0.9 g",
              "cholesterol": "0 mg",
              "saturatedFat": "0.0 g",
              "servingSize": "3 Ounce"
            },
            "name": "Plain Cooked Quinoa",
            "isVegetarian": true,
            "itemID": 5342429,
            "hasInfo": true,
            "meal": "Dinner"
          },
          {
            "isVegetarian": true,
            "itemID": 5366094,
            "hasInfo": true,
            "meal": "Dinner",
            "ingredients": [
              "Eggs",
              "Sugar",
              "Cake flour",
              "Milk",
              "Shortening",
              "Lemon extract",
              "Salt",
              "Baking powder",
              "Raspberry buttercream icing"
            ],
            "allergens": [
              "Alcohol",
              "Dairy",
              "Eggs",
              "Wheat",
              "Gluten"
            ],
            "isVegan": false,
            "isGlutenFree": false,
            "nutrition": {
              "vitaminC": "0.0 mg",
              "sugar": "29.0 g",
              "iron": "1.8 mg",
              "carbohydrates": "44.8 g",
              "fiber": "0.3 g",
              "protein": "4.8 g",
              "vitaminA": "135.3 IU",
              "calories": "268 cal",
              "fat": "7.2 g",
              "cholesterol": "105 mg",
              "saturatedFat": "3.0 g",
              "servingSize": "1 Serving"
            },
            "name": "Lemon Raspberry Sheet Cake"
          }
        ],
        "hotBreakfast": [],
        "contBreakfast": [],
        "lunch": []
      }
    }
  ]