    export const favoritesResponse = {
      "5342429": {
        "isBeingServed": false,
        "name": "Plain Cooked Quinoa",
      },
      "5416409": {
        "isBeingServed": true,
        "location": [
          "Berkeley",
          "Branford",
          "Grace Hopper",
          "Davenport",
          "Morse",
          "Jonathan Edwards",
          "Pierson",
          "Silliman",
          "Timothy Dwight",
          "Trumbull",
          "Saybrook",
          "Stiles",
          "Benjamin Franklin",
          "Pauli Murray",
        ],
        "meal": [
          "lunch",
          "dinner",
        ],
        "name": "Grass-Fed Hand-Shaped Cheeseburger",
      },
      "5525070": {
        "isBeingServed": false,
        "name": "Shredded Potato Hash Browns",
      },
      "5910277": {
        "isBeingServed": true,
        "location": [
          "Berkeley",
          "Branford",
          "Grace Hopper",
          "Davenport",
          "Morse",
          "Jonathan Edwards",
          "Pierson",
          "Silliman",
          "Timothy Dwight",
          "Trumbull",
          "Saybrook",
          "Stiles",
          "Benjamin Franklin",
          "Pauli Murray",
        ],
        "meal": [
          "contBreakfast",
          "hotBreakfast",
        ],
        "name": "Waffles",
      },
      "6784067": {
        "isBeingServed": true,
        "location": [
          "Berkeley",
          "Branford",
          "Grace Hopper",
          "Davenport",
          "Morse",
          "Jonathan Edwards",
          "Pierson",
          "Silliman",
          "Timothy Dwight",
          "Trumbull",
          "Saybrook",
          "Stiles",
          "Benjamin Franklin",
          "Pauli Murray",
        ],
        "meal": [
          "lunch",
          "dinner",
        ],
        "name": "Beyond Meat Burger",
      },
    }