export const menusResponse = {
      "location": "Davenport",
      "today":  {
        "brunch":  [],
        "contBreakfast": [
          {
            "allergens": [
              "Eggs",
            ],
            "hasInfo": true,
            "ingredients": [
              "Certified organic cage-free eggs",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 3952458,
            "meal": "Contl. Bkfst.",
            "name": "Certified Organic, Cage-Free Hard-Boiled Eggs",
            "nutrition": {
              "calories": "62 cal",
              "carbohydrates": "0.3 g",
              "cholesterol": "186 mg",
              "fat": "4.4 g",
              "fiber": "0.0 g",
              "iron": "0.8 mg",
              "protein": "5.5 g",
              "saturatedFat": "1.4 g",
              "servingSize": "1 Each",
              "sugar": "0.3 g",
              "vitaminA": "214.3 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Soy Milk",
              "All-Purpose Flour",
              "Powdered Sugar",
              "Baking Powder",
              "Earth Balance Vegan Butter Spread",
              "Vanilla Extract",
              "Baking Soda",
              "Kosher Salt",
              "Yellow Cornmeal",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5908402,
            "meal": "Contl. Bkfst.",
            "name": "Vegan Waffles",
            "nutrition": {
              "calories": "278 cal",
              "carbohydrates": "53.2 g",
              "cholesterol": "0 mg",
              "fat": "3.4 g",
              "fiber": "1.8 g",
              "iron": "2.9 mg",
              "protein": "7.5 g",
              "saturatedFat": "0.8 g",
              "servingSize": "1 Each",
              "sugar": "10.8 g",
              "vitaminA": "151.9 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Tap Water",
              "Waffle Mix",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 5910277,
            "meal": "Contl. Bkfst.",
            "name": "Waffles",
            "nutrition": {
              "calories": "276 cal",
              "carbohydrates": "54.3 g",
              "cholesterol": "0 mg",
              "fat": "3.1 g",
              "fiber": "1.0 g",
              "iron": "3.7 mg",
              "protein": "5.1 g",
              "saturatedFat": "0.0 g",
              "servingSize": "1 Serving",
              "sugar": "5.1 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Cake flour",
              "Unsalted butter",
              "All-purpose flour",
              "Half-",
              "-half",
              "Sour cream",
              "Superfine sugar",
              "Lemon zest",
              "Thyme",
              "Baking powder",
              "Baking soda",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 5506247,
            "meal": "Contl. Bkfst.",
            "name": "Lemon Thyme Scones",
            "nutrition": {
              "calories": "182 cal",
              "carbohydrates": "20.7 g",
              "cholesterol": "28 mg",
              "fat": "10.0 g",
              "fiber": "0.5 g",
              "iron": "1.4 mg",
              "protein": "2.4 g",
              "saturatedFat": "6.2 g",
              "servingSize": "1 Each",
              "sugar": "4.2 g",
              "vitaminA": "329.6 IU",
              "vitaminC": "1.1 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Tap Water",
              "Whole-Grain",
              "Steel-Cut Oats",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5890196,
            "meal": "Contl. Bkfst.",
            "name": "Whole-Grain Irish Oatmeal",
            "nutrition": {
              "calories": "104 cal",
              "carbohydrates": "17.8 g",
              "cholesterol": "0 mg",
              "fat": "1.9 g",
              "fiber": "3.1 g",
              "iron": "1.1 mg",
              "protein": "4.3 g",
              "saturatedFat": "0.3 g",
              "servingSize": "7.088 Ounce",
              "sugar": "0.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "0.0 mg",
            },
          },
        ],
        "dinner": [
          {
            "allergens": [
              "Shellfish",
              "Dairy",
              "Fish/Seafood",
              "Soy",
            ],
            "hasInfo": true,
            "ingredients": [
              "Wild mussels",
              "Coconut milk",
              "Red tomatoes",
              "Unsalted butter",
              "Red curry paste",
              "Cilantro",
              "Fresh ginger",
              "Garlic",
              "Kosher salt",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5650646,
            "meal": "Dinner",
            "name": "Red Curry Mussels",
            "nutrition": {
              "calories": "182 cal",
              "carbohydrates": "5.8 g",
              "cholesterol": "36 mg",
              "fat": "10.6 g",
              "fiber": "0.4 g",
              "iron": "5.0 mg",
              "protein": "13.6 g",
              "saturatedFat": "1.7 g",
              "servingSize": "6.4 Ounce",
              "sugar": "0.7 g",
              "vitaminA": "500.6 IU",
              "vitaminC": "12.8 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Chicken pieces",
              "Marinade singapore chicken fm",
              "Sub dry rub singapore chicken  fm",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5331731,
            "meal": "Dinner",
            "name": "Singapore Chicken",
            "nutrition": {
              "calories": "364 cal",
              "carbohydrates": "2.5 g",
              "cholesterol": "146 mg",
              "fat": "25.0 g",
              "fiber": "0.3 g",
              "iron": "3.1 mg",
              "protein": "31.0 g",
              "saturatedFat": "6.6 g",
              "servingSize": "6.4 Ounce",
              "sugar": "0.2 g",
              "vitaminA": "1122.9 IU",
              "vitaminC": "4.9 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Tap water",
              "Dried lentils",
              "Red onion",
              "Basmati rice",
              "Italian parsley",
              "Extra virgin olive oil",
              "Kosher salt",
              "Ground cinnamon",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 4353344,
            "meal": "Dinner",
            "name": "Mujaddarah Rice and Lentil Pilaf",
            "nutrition": {
              "calories": "131 cal",
              "carbohydrates": "29.4 g",
              "cholesterol": "0 mg",
              "fat": "1.4 g",
              "fiber": "6.8 g",
              "iron": "2.2 mg",
              "protein": "7.7 g",
              "saturatedFat": "0.2 g",
              "servingSize": "1 Serving",
              "sugar": "0.8 g",
              "vitaminA": "273.3 IU",
              "vitaminC": "5.7 mg",
            },
          },
          {
            "allergens": [
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Low-Sodium Chicken Stock",
              "Sub Matzo Ball",
              "Chicken Thighs",
              "Onions",
              "Carrots",
              "Dried Celery",
              "Fresh Dill",
              "Black Peppercorns",
              "Fresh Bay Leaves",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 3617831,
            "meal": "Dinner",
            "name": "Matzo Ball Soup",
            "nutrition": {
              "calories": "98 cal",
              "carbohydrates": "7.8 g",
              "cholesterol": "61 mg",
              "fat": "6.3 g",
              "fiber": "0.3 g",
              "iron": "0.2 mg",
              "protein": "2.7 g",
              "saturatedFat": "3.4 g",
              "servingSize": "6 Fluid Ounce",
              "sugar": "0.7 g",
              "vitaminA": "199.7 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Soy",
            ],
            "hasInfo": true,
            "ingredients": [
              "Low-sodium vegetable stock",
              "Leeks",
              "Yukon gold potatoes",
              "Onions",
              "Half-",
              "-half",
              "Canola oil",
              "Unsalted butter",
              "Ground white pepper",
              "Kosher salt",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 4389060,
            "meal": "Dinner",
            "name": "Potato Leek Soup with Frizzled Leeks",
            "nutrition": {
              "calories": "77 cal",
              "carbohydrates": "8.9 g",
              "cholesterol": "11 mg",
              "fat": "3.6 g",
              "fiber": "1.3 g",
              "iron": "1.2 mg",
              "protein": "2.2 g",
              "saturatedFat": "1.8 g",
              "servingSize": "6 Fluid Ounce",
              "sugar": "2.8 g",
              "vitaminA": "1013.3 IU",
              "vitaminC": "6.7 mg",
            },
          },
          {
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Fennel",
              "Extra virgin olive oil",
              "Canola oil",
              "Red wine vinegar",
              "Italian spice blend",
              "Radicchio",
              "Olive medley",
              "Housemade croutons",
              "Basil",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 4703638,
            "meal": "Dinner",
            "name": "Radicchio, Fennel, and Olive Panzanella Salad",
            "nutrition": {
              "calories": "216 cal",
              "carbohydrates": "5.5 g",
              "cholesterol": "0 mg",
              "fat": "21.7 g",
              "fiber": "1.5 g",
              "iron": "1.0 mg",
              "protein": "1.1 g",
              "saturatedFat": "2.3 g",
              "servingSize": "3 Ounce",
              "sugar": "0.2 g",
              "vitaminA": "125.4 IU",
              "vitaminC": "4.8 mg",
            },
          },
          {
            "allergens": [
              "Peanut",
            ],
            "hasInfo": true,
            "ingredients": [
              "Kohlrabi",
              "Brussels sprouts",
              "Broccoli",
              "Kale",
              "Red cabbage",
              "Carrots",
              "Tomatoes",
              "Peanuts",
              "Scallions",
              "Jalapeno peppers",
              "Ginger",
              "Lime juice",
              "Cilantro",
              "White wine vinegar",
              "Mint",
              "Granulated sugar",
              "Kosher salt",
              "Ground cumin",
              "Ground black pepper",
              "Cayenne pepper",
              "Chaat masala",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5419768,
            "meal": "Dinner",
            "name": "Superfood Slaw with Fresh Herb and Peanuts",
            "nutrition": {
              "calories": "46 cal",
              "carbohydrates": "4.5 g",
              "cholesterol": "0 mg",
              "fat": "2.5 g",
              "fiber": "1.9 g",
              "iron": "0.5 mg",
              "protein": "2.0 g",
              "saturatedFat": "0.4 g",
              "servingSize": "2 Ounce",
              "sugar": "1.5 g",
              "vitaminA": "1511.8 IU",
              "vitaminC": "23.7 mg",
            },
          },
          {
            "allergens": [
              "Nuts",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Wheat berries",
              "Dried apricot",
              "Golden raisins",
              "Walnuts",
              "Scallions",
              "Olive oil",
              "Canola blend",
              "Pancake syrup",
              "Orange juice concentrate",
              "Balsamic vinegar",
              "Basil",
              "Ginger",
              "Orange zest",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 4883833,
            "meal": "Dinner",
            "name": "Farro Salad with Raisins, Apricots, and Walnuts",
            "nutrition": {
              "calories": "204 cal",
              "carbohydrates": "35.0 g",
              "cholesterol": "0 mg",
              "fat": "5.7 g",
              "fiber": "5.7 g",
              "iron": "1.6 mg",
              "protein": "5.5 g",
              "saturatedFat": "0.6 g",
              "servingSize": "3 Ounce",
              "sugar": "10.0 g",
              "vitaminA": "376.5 IU",
              "vitaminC": "1.3 mg",
            },
          },
          {
            "allergens": [
              "Nuts",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Pea Protein",
              "Canola Oil",
              "Refined Coconut Oil",
              "Water",
              "Yeast Extract",
              "Maltodextrin",
              "Natural Flavors",
              "Gum Arabic",
              "Sunflower Oil",
              "Salt",
              "Succinic Acid",
              "Acetic Acid",
              "Non-Gmo Modified Food Starch",
              "Cellulose From Bamboo",
              "Methylcellulose",
              "Potato Starch",
              "Beet Juice Extract",
              "Ascorbi",
              "Wheat Hamburger Bun",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 6784067,
            "meal": "Dinner",
            "name": "Beyond Meat Burger",
            "nutrition": {
              "calories": "438 cal",
              "carbohydrates": "33.9 g",
              "cholesterol": "0 mg",
              "fat": "23.9 g",
              "fiber": "5.0 g",
              "iron": "1.4 mg",
              "protein": "25.9 g",
              "saturatedFat": "8.5 g",
              "servingSize": "1 Each",
              "sugar": "3.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "53.9 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Grass-Fed Ground Beef",
              "Mushroom Duxelles",
              "Kosher Salt",
              "Black Pepper",
              "Brioche Roll",
              "Better Burger Leaf Lettuce",
              "Tomato",
              "Vegan Mayo",
              "Lemon Juice",
              "Dill Pickle Relish",
              "Garlic Powder",
              "Paprika",
              "Less than  2% Silicon Dioxide",
              "Onion Powder",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5263541,
            "meal": "Dinner",
            "name": "Grass-Fed Hand Shaped Burger",
            "nutrition": {
              "calories": "397 cal",
              "carbohydrates": "29.2 g",
              "cholesterol": "85 mg",
              "fat": "21.5 g",
              "fiber": "2.1 g",
              "iron": "2.2 mg",
              "protein": "20.8 g",
              "saturatedFat": "9.1 g",
              "servingSize": "1 Sandwich",
              "sugar": "3.5 g",
              "vitaminA": "2219.9 IU",
              "vitaminC": "8.1 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Grass-Fed Ground Beef",
              "Mushroom Duxelles",
              "Kosher Salt",
              "Black Pepper",
              "Brioche Roll",
              "Better Burger Leaf Lettuce",
              "Tomatoes",
              "White Cheddar Cheese",
              "Vegan Mayo",
              "Lemon Juice",
              "Dill Pickle Relish",
              "Garlic Powder",
              "Paprika",
              "Less than  2% Silicon Dioxide",
              "Onion Powder",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5416409,
            "meal": "Dinner",
            "name": "Grass-Fed Hand-Shaped Cheeseburger",
            "nutrition": {
              "calories": "452 cal",
              "carbohydrates": "29.7 g",
              "cholesterol": "103 mg",
              "fat": "26.5 g",
              "fiber": "2.1 g",
              "iron": "2.2 mg",
              "protein": "24.4 g",
              "saturatedFat": "12.1 g",
              "servingSize": "1 Sandwich",
              "sugar": "3.5 g",
              "vitaminA": "2370.1 IU",
              "vitaminC": "8.1 mg",
            },
          },
          {
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Vegan Black Bean",
              "Sweet Potato Burger",
              "Wheat Hamburger Bun",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5926612,
            "meal": "Dinner",
            "name": "Vegan Sweet Potato and Black Bean Burger",
            "nutrition": {
              "calories": "239 cal",
              "carbohydrates": "43.0 g",
              "cholesterol": "0 mg",
              "fat": "3.5 g",
              "fiber": "5.0 g",
              "iron": "3.2 mg",
              "protein": "11.0 g",
              "saturatedFat": "0.5 g",
              "servingSize": "1 Each",
              "sugar": "5.0 g",
              "vitaminA": "1748.9 IU",
              "vitaminC": "6.0 mg",
            },
          },
          {
            "allergens": [
              "Soy",
            ],
            "hasInfo": true,
            "ingredients": [
              "Crimini mushrooms",
              "Edamame",
              "Extra virgin olive oil",
              "Lemon zest",
              "Italian parsley",
              "Italian basil",
              "Garlic",
              "Garlic powder",
              "Oregano",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 4137713,
            "meal": "Dinner",
            "name": "Cremini Mushrooms with Edamame",
            "nutrition": {
              "calories": "215 cal",
              "carbohydrates": "11.5 g",
              "cholesterol": "0 mg",
              "fat": "15.3 g",
              "fiber": "4.7 g",
              "iron": "2.3 mg",
              "protein": "10.4 g",
              "saturatedFat": "2.0 g",
              "servingSize": "6 Ounce",
              "sugar": "3.0 g",
              "vitaminA": "190.8 IU",
              "vitaminC": "9.5 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Cauliflower",
              "Olive oil",
              "Canola blend",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5520835,
            "meal": "Dinner",
            "name": "Roasted Cauliflower",
            "nutrition": {
              "calories": "74 cal",
              "carbohydrates": "7.0 g",
              "cholesterol": "0 mg",
              "fat": "4.5 g",
              "fiber": "3.3 g",
              "iron": "0.6 mg",
              "protein": "2.6 g",
              "saturatedFat": "0.7 g",
              "servingSize": "4 Ounce",
              "sugar": "3.2 g",
              "vitaminA": "17.1 IU",
              "vitaminC": "60.9 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Tap water",
              "Basmati rice",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5163221,
            "meal": "Dinner",
            "name": "Basmati Rice",
            "nutrition": {
              "calories": "97 cal",
              "carbohydrates": "21.5 g",
              "cholesterol": "0 mg",
              "fat": "0.3 g",
              "fiber": "0.0 g",
              "iron": "0.0 mg",
              "protein": "2.6 g",
              "saturatedFat": "0.0 g",
              "servingSize": "3 Ounce",
              "sugar": "0.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Sweetened condensed milk",
              "Whipped topping",
              "Graham cracker pie shells",
              "Key lime juice",
              "Lime zest",
              "Egg yolks",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 5230508,
            "meal": "Dinner",
            "name": "Key Lime Pie",
            "nutrition": {
              "calories": "478 cal",
              "carbohydrates": "58.7 g",
              "cholesterol": "149 mg",
              "fat": "24.8 g",
              "fiber": "1.2 g",
              "iron": "0.9 mg",
              "protein": "8.3 g",
              "saturatedFat": "17.9 g",
              "servingSize": "1 Serving",
              "sugar": "45.8 g",
              "vitaminA": "347.8 IU",
              "vitaminC": "4.2 mg",
            },
          },
        ],
        "hotBreakfast": [],
        "lunch": [
          {
            "allergens": [
              "Alcohol",
            ],
            "hasInfo": true,
            "ingredients": [
              "Turkey breast",
              "Tap water",
              "Chablis cooking wine",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 4235396,
            "meal": "Lunch",
            "name": "Roast Turkey Breast",
            "nutrition": {
              "calories": "90 cal",
              "carbohydrates": "0.0 g",
              "cholesterol": "34 mg",
              "fat": "3.1 g",
              "fiber": "0.0 g",
              "iron": "0.4 mg",
              "protein": "15.4 g",
              "saturatedFat": "0.9 g",
              "servingSize": "3 Ounce",
              "sugar": "0.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "1.5 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Low-sodium black-eyed peas",
              "Kale",
              "Tomatoes",
              "Scallions",
              "Italian parsley",
              "Olive oil",
              "Canola blend",
              "Lemon juice",
              "Oregano",
              "Kosher salt",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 46122,
            "meal": "Lunch",
            "name": "Yale Eyed Peas with Greens",
            "nutrition": {
              "calories": "118 cal",
              "carbohydrates": "15.9 g",
              "cholesterol": "0 mg",
              "fat": "4.4 g",
              "fiber": "3.5 g",
              "iron": "1.1 mg",
              "protein": "4.9 g",
              "saturatedFat": "0.6 g",
              "servingSize": "6 Ounce",
              "sugar": "1.3 g",
              "vitaminA": "6398.4 IU",
              "vitaminC": "56.1 mg",
            },
          },
          {
            "allergens": [
              "Alcohol",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Whole wheat penne pasta",
              "Fennel",
              "Tomatoes",
              "Vegan soy sausage crumble",
              "Spanish onions",
              "Swiss  chard",
              "Low-sodium vegetable stock",
              "Chablis cooking wine",
              "Kalamata olives",
              "Extra virgin olive oil",
              "Lemon juice",
              "Garlic",
              "Thyme",
              "Parsley",
              "Tarragon",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 4185056,
            "meal": "Lunch",
            "name": "Whole-Wheat Penne Pasta with Soy Sausage, Tomatoes, Fennel, and Swiss Chard",
            "nutrition": {
              "calories": "299 cal",
              "carbohydrates": "46.5 g",
              "cholesterol": "0 mg",
              "fat": "6.8 g",
              "fiber": "9.0 g",
              "iron": "3.0 mg",
              "protein": "14.3 g",
              "saturatedFat": "0.4 g",
              "servingSize": "9 Ounce",
              "sugar": "4.1 g",
              "vitaminA": "1114.1 IU",
              "vitaminC": "15.8 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Eggs",
              "Fish/Seafood",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Chesapeake bay wild blue catfish",
              "Cage-free liquid eggs",
              "Buttermilk",
              "Fine cracker meal",
              "Italian parsley",
              "Yellow cornmeal",
              "Tabasco sauce",
              "Kosher salt",
              "Garlic powder",
              "Granulated onion",
              "Cayenne pepper",
              "Ground mustard",
              "Ground black pepper",
              "Celery seeds",
              "Oregano",
              "Dried thyme",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 4674681,
            "meal": "Lunch",
            "name": "Cornmeal-Crusted Wild Catfish",
            "nutrition": {
              "calories": "191 cal",
              "carbohydrates": "5.7 g",
              "cholesterol": "101 mg",
              "fat": "9.6 g",
              "fiber": "0.3 g",
              "iron": "1.1 mg",
              "protein": "19.3 g",
              "saturatedFat": "2.4 g",
              "servingSize": "5 Ounce",
              "sugar": "0.7 g",
              "vitaminA": "190.5 IU",
              "vitaminC": "1.8 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Soy",
            ],
            "hasInfo": true,
            "ingredients": [
              "Low-sodium vegetable stock",
              "Leeks",
              "Yukon gold potatoes",
              "Onions",
              "Half-",
              "-half",
              "Canola oil",
              "Unsalted butter",
              "Ground white pepper",
              "Kosher salt",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 4389060,
            "meal": "Lunch",
            "name": "Potato Leek Soup with Frizzled Leeks",
            "nutrition": {
              "calories": "77 cal",
              "carbohydrates": "8.9 g",
              "cholesterol": "11 mg",
              "fat": "3.6 g",
              "fiber": "1.3 g",
              "iron": "1.2 mg",
              "protein": "2.2 g",
              "saturatedFat": "1.8 g",
              "servingSize": "6 Fluid Ounce",
              "sugar": "2.8 g",
              "vitaminA": "1013.3 IU",
              "vitaminC": "6.7 mg",
            },
          },
          {
            "allergens": [
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Low-Sodium Chicken Stock",
              "Sub Matzo Ball",
              "Chicken Thighs",
              "Onions",
              "Carrots",
              "Dried Celery",
              "Fresh Dill",
              "Black Peppercorns",
              "Fresh Bay Leaves",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 3617831,
            "meal": "Lunch",
            "name": "Matzo Ball Soup",
            "nutrition": {
              "calories": "98 cal",
              "carbohydrates": "7.8 g",
              "cholesterol": "61 mg",
              "fat": "6.3 g",
              "fiber": "0.3 g",
              "iron": "0.2 mg",
              "protein": "2.7 g",
              "saturatedFat": "3.4 g",
              "servingSize": "6 Fluid Ounce",
              "sugar": "0.7 g",
              "vitaminA": "199.7 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Fennel",
              "Extra virgin olive oil",
              "Canola oil",
              "Red wine vinegar",
              "Italian spice blend",
              "Radicchio",
              "Olive medley",
              "Housemade croutons",
              "Basil",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 4703638,
            "meal": "Lunch",
            "name": "Radicchio, Fennel, and Olive Panzanella Salad",
            "nutrition": {
              "calories": "216 cal",
              "carbohydrates": "5.5 g",
              "cholesterol": "0 mg",
              "fat": "21.7 g",
              "fiber": "1.5 g",
              "iron": "1.0 mg",
              "protein": "1.1 g",
              "saturatedFat": "2.3 g",
              "servingSize": "3 Ounce",
              "sugar": "0.2 g",
              "vitaminA": "125.4 IU",
              "vitaminC": "4.8 mg",
            },
          },
          {
            "allergens": [
              "Peanut",
            ],
            "hasInfo": true,
            "ingredients": [
              "Kohlrabi",
              "Brussels sprouts",
              "Broccoli",
              "Kale",
              "Red cabbage",
              "Carrots",
              "Tomatoes",
              "Peanuts",
              "Scallions",
              "Jalapeno peppers",
              "Ginger",
              "Lime juice",
              "Cilantro",
              "White wine vinegar",
              "Mint",
              "Granulated sugar",
              "Kosher salt",
              "Ground cumin",
              "Ground black pepper",
              "Cayenne pepper",
              "Chaat masala",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5419768,
            "meal": "Lunch",
            "name": "Superfood Slaw with Fresh Herb and Peanuts",
            "nutrition": {
              "calories": "46 cal",
              "carbohydrates": "4.5 g",
              "cholesterol": "0 mg",
              "fat": "2.5 g",
              "fiber": "1.9 g",
              "iron": "0.5 mg",
              "protein": "2.0 g",
              "saturatedFat": "0.4 g",
              "servingSize": "2 Ounce",
              "sugar": "1.5 g",
              "vitaminA": "1511.8 IU",
              "vitaminC": "23.7 mg",
            },
          },
          {
            "allergens": [
              "Nuts",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Wheat berries",
              "Dried apricot",
              "Golden raisins",
              "Walnuts",
              "Scallions",
              "Olive oil",
              "Canola blend",
              "Pancake syrup",
              "Orange juice concentrate",
              "Balsamic vinegar",
              "Basil",
              "Ginger",
              "Orange zest",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 4883833,
            "meal": "Lunch",
            "name": "Farro Salad with Raisins, Apricots, and Walnuts",
            "nutrition": {
              "calories": "204 cal",
              "carbohydrates": "35.0 g",
              "cholesterol": "0 mg",
              "fat": "5.7 g",
              "fiber": "5.7 g",
              "iron": "1.6 mg",
              "protein": "5.5 g",
              "saturatedFat": "0.6 g",
              "servingSize": "3 Ounce",
              "sugar": "10.0 g",
              "vitaminA": "376.5 IU",
              "vitaminC": "1.3 mg",
            },
          },
          {
            "allergens": [
              "Nuts",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Pea Protein",
              "Canola Oil",
              "Refined Coconut Oil",
              "Water",
              "Yeast Extract",
              "Maltodextrin",
              "Natural Flavors",
              "Gum Arabic",
              "Sunflower Oil",
              "Salt",
              "Succinic Acid",
              "Acetic Acid",
              "Non-Gmo Modified Food Starch",
              "Cellulose From Bamboo",
              "Methylcellulose",
              "Potato Starch",
              "Beet Juice Extract",
              "Ascorbi",
              "Wheat Hamburger Bun",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 6784067,
            "meal": "Lunch",
            "name": "Beyond Meat Burger",
            "nutrition": {
              "calories": "438 cal",
              "carbohydrates": "33.9 g",
              "cholesterol": "0 mg",
              "fat": "23.9 g",
              "fiber": "5.0 g",
              "iron": "1.4 mg",
              "protein": "25.9 g",
              "saturatedFat": "8.5 g",
              "servingSize": "1 Each",
              "sugar": "3.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "53.9 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Grass-Fed Ground Beef",
              "Mushroom Duxelles",
              "Kosher Salt",
              "Black Pepper",
              "Brioche Roll",
              "Better Burger Leaf Lettuce",
              "Tomato",
              "Vegan Mayo",
              "Lemon Juice",
              "Dill Pickle Relish",
              "Garlic Powder",
              "Paprika",
              "Less than  2% Silicon Dioxide",
              "Onion Powder",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5263541,
            "meal": "Lunch",
            "name": "Grass-Fed Hand Shaped Burger",
            "nutrition": {
              "calories": "397 cal",
              "carbohydrates": "29.2 g",
              "cholesterol": "85 mg",
              "fat": "21.5 g",
              "fiber": "2.1 g",
              "iron": "2.2 mg",
              "protein": "20.8 g",
              "saturatedFat": "9.1 g",
              "servingSize": "1 Sandwich",
              "sugar": "3.5 g",
              "vitaminA": "2219.9 IU",
              "vitaminC": "8.1 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Grass-Fed Ground Beef",
              "Mushroom Duxelles",
              "Kosher Salt",
              "Black Pepper",
              "Brioche Roll",
              "Better Burger Leaf Lettuce",
              "Tomatoes",
              "White Cheddar Cheese",
              "Vegan Mayo",
              "Lemon Juice",
              "Dill Pickle Relish",
              "Garlic Powder",
              "Paprika",
              "Less than  2% Silicon Dioxide",
              "Onion Powder",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5416409,
            "meal": "Lunch",
            "name": "Grass-Fed Hand-Shaped Cheeseburger",
            "nutrition": {
              "calories": "452 cal",
              "carbohydrates": "29.7 g",
              "cholesterol": "103 mg",
              "fat": "26.5 g",
              "fiber": "2.1 g",
              "iron": "2.2 mg",
              "protein": "24.4 g",
              "saturatedFat": "12.1 g",
              "servingSize": "1 Sandwich",
              "sugar": "3.5 g",
              "vitaminA": "2370.1 IU",
              "vitaminC": "8.1 mg",
            },
          },
          {
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Vegan Black Bean",
              "Sweet Potato Burger",
              "Wheat Hamburger Bun",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5926612,
            "meal": "Lunch",
            "name": "Vegan Sweet Potato and Black Bean Burger",
            "nutrition": {
              "calories": "239 cal",
              "carbohydrates": "43.0 g",
              "cholesterol": "0 mg",
              "fat": "3.5 g",
              "fiber": "5.0 g",
              "iron": "3.2 mg",
              "protein": "11.0 g",
              "saturatedFat": "0.5 g",
              "servingSize": "1 Each",
              "sugar": "5.0 g",
              "vitaminA": "1748.9 IU",
              "vitaminC": "6.0 mg",
            },
          },
          {
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Soy milk",
              "All-purpose flour",
              "Cornmeal",
              "Superfine sugar",
              "Extra virgin olive oil",
              "Salt",
              "Baking soda",
              "White vinegar",
              "Corn",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5659579,
            "meal": "Lunch",
            "name": "Vegan Cornbread",
            "nutrition": {
              "calories": "130 cal",
              "carbohydrates": "21.4 g",
              "cholesterol": "0 mg",
              "fat": "3.9 g",
              "fiber": "0.7 g",
              "iron": "0.9 mg",
              "protein": "2.1 g",
              "saturatedFat": "0.5 g",
              "servingSize": "1 Serving",
              "sugar": "6.7 g",
              "vitaminA": "42.4 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Soy",
            ],
            "hasInfo": true,
            "ingredients": [
              "Collard greens",
              "Onions",
              "Low-sodium vegetable stock",
              "Apple cider vinegar",
              "Local honey",
              "Extra virgin olive oil",
              "Kosher salt",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 822736,
            "meal": "Lunch",
            "name": "Southern-Style Collard Greens",
            "nutrition": {
              "calories": "52 cal",
              "carbohydrates": "8.1 g",
              "cholesterol": "0 mg",
              "fat": "2.0 g",
              "fiber": "3.5 g",
              "iron": "0.2 mg",
              "protein": "2.4 g",
              "saturatedFat": "0.3 g",
              "servingSize": "4 Ounce",
              "sugar": "2.8 g",
              "vitaminA": "6248.9 IU",
              "vitaminC": "33.7 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Cauliflower crown",
              "Olive oil",
              "Canola blend",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": true,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5407483,
            "meal": "Lunch",
            "name": "Roasted Cauliflower",
            "nutrition": {
              "calories": "76 cal",
              "carbohydrates": "7.2 g",
              "cholesterol": "0 mg",
              "fat": "4.6 g",
              "fiber": "3.4 g",
              "iron": "0.6 mg",
              "protein": "2.7 g",
              "saturatedFat": "0.7 g",
              "servingSize": "1 Serving",
              "sugar": "3.3 g",
              "vitaminA": "17.7 IU",
              "vitaminC": "63.1 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Tap water",
              "Long grain parboiled brown rice; sprouted brown rice; colusari red rice; sprouted sienna red rice; wild rice",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 3514666,
            "meal": "Lunch",
            "name": "Ruby Red Rice Blend",
            "nutrition": {
              "calories": "0 cal",
              "carbohydrates": "0.0 g",
              "cholesterol": "0 mg",
              "fat": "0.0 g",
              "fiber": "0.0 g",
              "iron": "0.0 mg",
              "protein": "0.0 g",
              "saturatedFat": "0.0 g",
              "servingSize": "3 Ounce",
              "sugar": "0.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Alcohol",
              "Dairy",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Ciabatta roll",
              "Whole wheat tortillas",
              "Sauce chermoula",
              "Sauce barbecue harissa",
              "Lemon;mint;cultured grade a non fat milk",
              "Contians active yogurt cultures including l",
              "Acidophilus;honey;extra virgin olive oil",
              "Canola oil;italian parsley;kosher salt;white ground pepper;",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 4615023,
            "meal": "Lunch",
            "name": "Carved Turkey Accompaniments",
            "nutrition": {
              "calories": "461 cal",
              "carbohydrates": "53.4 g",
              "cholesterol": "0 mg",
              "fat": "23.9 g",
              "fiber": "4.2 g",
              "iron": "3.2 mg",
              "protein": "10.2 g",
              "saturatedFat": "2.8 g",
              "servingSize": "1 Serving",
              "sugar": "6.9 g",
              "vitaminA": "591.1 IU",
              "vitaminC": "12.4 mg",
            },
          },
          {
            "allergens": [
              "Alcohol",
              "Nuts",
              "Dairy",
              "Eggs",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Light brown sugar",
              "All-purpose flour",
              "Unsalted butter",
              "Rolled oats",
              "Semisweet chocolate chip",
              "Cranberries",
              "Shredded coconut",
              "White chocolate chips",
              "Eggs",
              "Pecans",
              "Baking powder",
              "Baking soda",
              "Salt",
              "Pure vanilla extract",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 5334526,
            "meal": "Lunch",
            "name": "Kitchen Sink Cookies",
            "nutrition": {
              "calories": "211 cal",
              "carbohydrates": "28.3 g",
              "cholesterol": "27 mg",
              "fat": "10.5 g",
              "fiber": "1.4 g",
              "iron": "1.1 mg",
              "protein": "2.6 g",
              "saturatedFat": "6.0 g",
              "servingSize": "1 Cookie",
              "sugar": "17.5 g",
              "vitaminA": "212.7 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Alcohol",
              "Dairy",
              "Eggs",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Superfine sugar",
              "Cream cheese",
              "Unsalted butter",
              "All-purpose flour",
              "Eggs",
              "Dutch bakers cocoa",
              "Pure vanilla extract",
              "Baking powder",
              "Salt",
              "Milk",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5066741,
            "meal": "Lunch",
            "name": "Cream Cheese Brownies",
            "nutrition": {
              "calories": "465 cal",
              "carbohydrates": "60.7 g",
              "cholesterol": "118 mg",
              "fat": "23.6 g",
              "fiber": "3.1 g",
              "iron": "2.1 mg",
              "protein": "5.6 g",
              "saturatedFat": "14.8 g",
              "servingSize": "1 Serving",
              "sugar": "45.0 g",
              "vitaminA": "768.4 IU",
              "vitaminC": "0.0 mg",
            },
          },
        ],
      },
      "tomorrow": {
        "brunch": [],
        "contBreakfast": [
          {
            "allergens": [
              "Eggs",
            ],
            "hasInfo": true,
            "ingredients": [
              "Certified organic cage-free eggs",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 3952458,
            "meal": "Contl. Bkfst.",
            "name": "Certified Organic, Cage-Free Hard-Boiled Eggs",
            "nutrition": {
              "calories": "62 cal",
              "carbohydrates": "0.3 g",
              "cholesterol": "186 mg",
              "fat": "4.4 g",
              "fiber": "0.0 g",
              "iron": "0.8 mg",
              "protein": "5.5 g",
              "saturatedFat": "1.4 g",
              "servingSize": "1 Each",
              "sugar": "0.3 g",
              "vitaminA": "214.3 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Soy milk",
              "All-purpose flour",
              "Powdered sugar",
              "Baking powder",
              "Earth balance vegan butter spread",
              "Vanilla extract",
              "Baking soda",
              "Kosher salt",
              "Yellow cornmeal",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5908402,
            "meal": "Contl. Bkfst.",
            "name": "Vegan Waffles",
            "nutrition": {
              "calories": "278 cal",
              "carbohydrates": "53.2 g",
              "cholesterol": "0 mg",
              "fat": "3.4 g",
              "fiber": "1.8 g",
              "iron": "2.9 mg",
              "protein": "7.5 g",
              "saturatedFat": "0.8 g",
              "servingSize": "1 Each",
              "sugar": "10.8 g",
              "vitaminA": "151.9 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Tap water",
              "Waffle mix",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 5910277,
            "meal": "Contl. Bkfst.",
            "name": "Waffles",
            "nutrition": {
              "calories": "276 cal",
              "carbohydrates": "54.3 g",
              "cholesterol": "0 mg",
              "fat": "3.1 g",
              "fiber": "1.0 g",
              "iron": "3.7 mg",
              "protein": "5.1 g",
              "saturatedFat": "0.0 g",
              "servingSize": "1 Serving",
              "sugar": "5.1 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Alcohol",
              "Dairy",
              "Eggs",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "All-purpose flour",
              "Milk",
              "Superfine sugar",
              "Eggs",
              "Unsalted butter",
              "Clover honey",
              "Baking powder",
              "Poppy seeds",
              "Lemon extract",
              "Salt",
              "Pure vanilla extract",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 5358681,
            "meal": "Contl. Bkfst.",
            "name": "Lemon-Poppyseed Muffins",
            "nutrition": {
              "calories": "327 cal",
              "carbohydrates": "52.0 g",
              "cholesterol": "70 mg",
              "fat": "10.4 g",
              "fiber": "1.0 g",
              "iron": "2.1 mg",
              "protein": "5.8 g",
              "saturatedFat": "6.0 g",
              "servingSize": "1 Each",
              "sugar": "24.8 g",
              "vitaminA": "348.7 IU",
              "vitaminC": "0.1 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Tap water",
              "Whole-grain",
              "Steel-cut oats",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5890196,
            "meal": "Contl. Bkfst.",
            "name": "Whole-Grain Irish Oatmeal",
            "nutrition": {
              "calories": "104 cal",
              "carbohydrates": "17.8 g",
              "cholesterol": "0 mg",
              "fat": "1.9 g",
              "fiber": "3.1 g",
              "iron": "1.1 mg",
              "protein": "4.3 g",
              "saturatedFat": "0.3 g",
              "servingSize": "7.088 Ounce",
              "sugar": "0.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "0.0 mg",
            },
          },
        ],
        "dinner": [
          {
            "allergens": [
              "Soy",
            ],
            "hasInfo": true,
            "ingredients": [
              "Low-sodium vegetable stock",
              "Plum tomatoes",
              "Corn",
              "Onions",
              "Dried celery",
              "Ground cori",
              "Er",
              "Kosher salt",
              "Garlic",
              "Canola oil",
              "Ground black pepper",
              "Dried thyme",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5676883,
            "meal": "Dinner",
            "name": "Roasted Corn and Tomato Soup",
            "nutrition": {
              "calories": "70 cal",
              "carbohydrates": "13.7 g",
              "cholesterol": "0 mg",
              "fat": "1.6 g",
              "fiber": "2.4 g",
              "iron": "0.5 mg",
              "protein": "2.7 g",
              "saturatedFat": "0.1 g",
              "servingSize": "6 Fluid Ounce",
              "sugar": "4.5 g",
              "vitaminA": "1378.9 IU",
              "vitaminC": "11.9 mg",
            },
          },
          {
            "allergens": [
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Low-sodium chicken stock",
              "Sub matzo ball",
              "Chicken thighs",
              "Onions",
              "Carrots",
              "Dried celery",
              "Fresh dill",
              "Black peppercorns",
              "Fresh bay leaves",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 3617831,
            "meal": "Dinner",
            "name": "Matzo Ball Soup",
            "nutrition": {
              "calories": "98 cal",
              "carbohydrates": "7.8 g",
              "cholesterol": "61 mg",
              "fat": "6.3 g",
              "fiber": "0.3 g",
              "iron": "0.2 mg",
              "protein": "2.7 g",
              "saturatedFat": "3.4 g",
              "servingSize": "6 Fluid Ounce",
              "sugar": "0.7 g",
              "vitaminA": "199.7 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Green garbanzo beans",
              "Avocado-lime vinaigrette",
              "Apples",
              "Crispy chickpeas",
              "Cilantro",
              "Carrots",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 3362345,
            "meal": "Dinner",
            "name": "Fresh Green Garbanzo Salad with Apples, Avocado-Lime Vinaigrette, and Crispy Chickpeas",
            "nutrition": {
              "calories": "131 cal",
              "carbohydrates": "12.0 g",
              "cholesterol": "0 mg",
              "fat": "7.6 g",
              "fiber": "3.2 g",
              "iron": "1.1 mg",
              "protein": "3.6 g",
              "saturatedFat": "1.0 g",
              "servingSize": "3 Ounce",
              "sugar": "2.0 g",
              "vitaminA": "541.3 IU",
              "vitaminC": "16.2 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
            ],
            "hasInfo": true,
            "ingredients": [
              "Wild baby arugula",
              "Cannellini beans",
              "Feta cheese",
              "Tomatoes",
              "Cucumber",
              "Kalamata olives",
              "Red onions",
              "Extra virgin olive oil",
              "Pepperoncini peppers",
              "Lemon juice",
              "Red wine vinegar",
              "Parsley",
              "Mint",
              "Garlic",
              "Curly parsley",
              "Oregano",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 3871561,
            "meal": "Dinner",
            "name": "Greek Salad with Arugula",
            "nutrition": {
              "calories": "72 cal",
              "carbohydrates": "4.6 g",
              "cholesterol": "7 mg",
              "fat": "5.0 g",
              "fiber": "1.4 g",
              "iron": "0.9 mg",
              "protein": "3.3 g",
              "saturatedFat": "1.6 g",
              "servingSize": "3 Ounce",
              "sugar": "1.5 g",
              "vitaminA": "1113.7 IU",
              "vitaminC": "8.7 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Quinoa",
              "Low-sodium black beans",
              "Bell peppers",
              "Corn kernels",
              "Scallions",
              "Extra virgin olive oil",
              "Lime juice",
              "Cilantro",
              "Kosher salt",
              "Ground cumin",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5348503,
            "meal": "Dinner",
            "name": "Southwest Quinoa Salad",
            "nutrition": {
              "calories": "105 cal",
              "carbohydrates": "15.8 g",
              "cholesterol": "0 mg",
              "fat": "3.8 g",
              "fiber": "1.8 g",
              "iron": "0.9 mg",
              "protein": "3.0 g",
              "saturatedFat": "0.4 g",
              "servingSize": "3 Ounce",
              "sugar": "1.5 g",
              "vitaminA": "136.7 IU",
              "vitaminC": "19.6 mg",
            },
          },
          {
            "allergens": [
              "Nuts",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Pea protein",
              "Canola oil",
              "Refined coconut oil",
              "Water",
              "Yeast extract",
              "Maltodextrin",
              "Natural flavors",
              "Gum arabic",
              "Sunflower oil",
              "Salt",
              "Succinic acid",
              "Acetic acid",
              "Non-gmo modified food starch",
              "Cellulose from bamboo",
              "Methylcellulose",
              "Potato starch",
              "Beet juice extract",
              "Ascorbi",
              "Wheat hamburger bun",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 6784067,
            "meal": "Dinner",
            "name": "Beyond Meat Burger",
            "nutrition": {
              "calories": "438 cal",
              "carbohydrates": "33.9 g",
              "cholesterol": "0 mg",
              "fat": "23.9 g",
              "fiber": "5.0 g",
              "iron": "1.4 mg",
              "protein": "25.9 g",
              "saturatedFat": "8.5 g",
              "servingSize": "1 Each",
              "sugar": "3.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "53.9 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Grass-fed ground beef",
              "Mushroom duxelles",
              "Kosher salt",
              "Black pepper",
              "Brioche roll",
              "Better burger leaf lettuce",
              "Tomato",
              "Vegan mayo",
              "Lemon juice",
              "Dill pickle relish",
              "Garlic powder",
              "Paprika",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5263541,
            "meal": "Dinner",
            "name": "Grass-Fed Hand Shaped Burger",
            "nutrition": {
              "calories": "397 cal",
              "carbohydrates": "29.2 g",
              "cholesterol": "85 mg",
              "fat": "21.5 g",
              "fiber": "2.1 g",
              "iron": "2.2 mg",
              "protein": "20.8 g",
              "saturatedFat": "9.1 g",
              "servingSize": "1 Sandwich",
              "sugar": "3.5 g",
              "vitaminA": "2219.9 IU",
              "vitaminC": "8.1 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Grass-fed ground beef",
              "Mushroom duxelles",
              "Kosher salt",
              "Black pepper",
              "Brioche roll",
              "Better burger leaf lettuce",
              "Tomatoes",
              "White cheddar cheese",
              "Vegan mayo",
              "Lemon juice",
              "Dill pickle relish",
              "Garlic powder",
              "Paprika",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5416409,
            "meal": "Dinner",
            "name": "Grass-Fed Hand-Shaped Cheeseburger",
            "nutrition": {
              "calories": "452 cal",
              "carbohydrates": "29.7 g",
              "cholesterol": "103 mg",
              "fat": "26.5 g",
              "fiber": "2.1 g",
              "iron": "2.2 mg",
              "protein": "24.4 g",
              "saturatedFat": "12.1 g",
              "servingSize": "1 Sandwich",
              "sugar": "3.5 g",
              "vitaminA": "2370.1 IU",
              "vitaminC": "8.1 mg",
            },
          },
          {
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Vegan black bean",
              "Sweet potato burger",
              "Wheat hamburger bun",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5926612,
            "meal": "Dinner",
            "name": "Vegan Sweet Potato and Black Bean Burger",
            "nutrition": {
              "calories": "239 cal",
              "carbohydrates": "43.0 g",
              "cholesterol": "0 mg",
              "fat": "3.5 g",
              "fiber": "5.0 g",
              "iron": "3.2 mg",
              "protein": "11.0 g",
              "saturatedFat": "0.5 g",
              "servingSize": "1 Each",
              "sugar": "5.0 g",
              "vitaminA": "1748.9 IU",
              "vitaminC": "6.0 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Broccoli florets",
              "Extra virgin olive oil",
              "Garlic",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 6087687,
            "meal": "Dinner",
            "name": "Sauteed Broccoli with Garlic",
            "nutrition": {
              "calories": "84 cal",
              "carbohydrates": "7.4 g",
              "cholesterol": "0 mg",
              "fat": "5.7 g",
              "fiber": "2.8 g",
              "iron": "0.8 mg",
              "protein": "3.1 g",
              "saturatedFat": "0.8 g",
              "servingSize": "4 Ounce",
              "sugar": "1.8 g",
              "vitaminA": "665.6 IU",
              "vitaminC": "95.6 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Long-grain brown rice",
              "Tap water",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 4166320,
            "meal": "Dinner",
            "name": "Steamed Brown Rice",
            "nutrition": {
              "calories": "231 cal",
              "carbohydrates": "49.4 g",
              "cholesterol": "0 mg",
              "fat": "1.5 g",
              "fiber": "1.5 g",
              "iron": "0.6 mg",
              "protein": "4.6 g",
              "saturatedFat": "0.0 g",
              "servingSize": "4 Ounce",
              "sugar": "0.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Alcohol",
              "Nuts",
              "Dairy",
              "Eggs",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Superfine sugar",
              "Carrots",
              "All-purpose flour",
              "Egg whites",
              "Whole-wheat flour",
              "Milk",
              "Almonds",
              "Raisins",
              "Canola oil",
              "Roasted pistachios",
              "Baking soda",
              "Baking powder",
              "Pure vanilla extract",
              "Ground cinnamon",
              "Pumpkin puree",
              "Ground cardamom",
              "Salt",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 5327197,
            "meal": "Dinner",
            "name": "Indian Spice Carrot Cupcakes",
            "nutrition": {
              "calories": "244 cal",
              "carbohydrates": "40.0 g",
              "cholesterol": "0 mg",
              "fat": "7.6 g",
              "fiber": "2.7 g",
              "iron": "1.5 mg",
              "protein": "5.1 g",
              "saturatedFat": "0.7 g",
              "servingSize": "1 Each",
              "sugar": "23.1 g",
              "vitaminA": "2443.0 IU",
              "vitaminC": "1.2 mg",
            },
          },
        ],
        "hotBreakfast": [],
        "lunch": [
          {
            "allergens": [
              "Dairy",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "All-natural grass-fed ground beef",
              "Flour tortillas",
              "Onions",
              "Tomatoes",
              "Cheddar cheese",
              "Shredded lettuce",
              "Taco shell",
              "Extra virgin olive oil",
              "Dark chili powder",
              "Kosher salt",
              "Spanish paprika",
              "Ground black pepper",
              "Ground cumin",
              "Cayenne pepper",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5471783,
            "meal": "Lunch",
            "name": "Ground Beef Tacos",
            "nutrition": {
              "calories": "396 cal",
              "carbohydrates": "21.4 g",
              "cholesterol": "74 mg",
              "fat": "25.5 g",
              "fiber": "2.3 g",
              "iron": "2.1 mg",
              "protein": "21.1 g",
              "saturatedFat": "10.7 g",
              "servingSize": "1 Taco",
              "sugar": "2.1 g",
              "vitaminA": "415.1 IU",
              "vitaminC": "4.1 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Chicken thighs",
              "Sub spice blend mexican fm",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 7950427,
            "meal": "Lunch",
            "name": "Chicken Thigh Carnitas",
            "nutrition": {
              "calories": "163 cal",
              "carbohydrates": "0.2 g",
              "cholesterol": "96 mg",
              "fat": "8.1 g",
              "fiber": "0.0 g",
              "iron": "4.1 mg",
              "protein": "22.3 g",
              "saturatedFat": "2.0 g",
              "servingSize": "1 Serving",
              "sugar": "0.2 g",
              "vitaminA": "24.7 IU",
              "vitaminC": "0.1 mg",
            },
          },
          {
            "allergens": [
              "Soy",
            ],
            "hasInfo": true,
            "ingredients": [
              "Low-sodium vegetable stock",
              "Black beans",
              "Onions",
              "Sun-dried tomatoes",
              "Extra virgin olive oil",
              "Chipotle peppers in adobo",
              "Garlic",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 399283,
            "meal": "Lunch",
            "name": "Stewed Black Beans",
            "nutrition": {
              "calories": "96 cal",
              "carbohydrates": "21.9 g",
              "cholesterol": "0 mg",
              "fat": "2.7 g",
              "fiber": "12.0 g",
              "iron": "2.7 mg",
              "protein": "7.9 g",
              "saturatedFat": "0.3 g",
              "servingSize": "3.76 Ounce",
              "sugar": "3.9 g",
              "vitaminA": "307.5 IU",
              "vitaminC": "3.4 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Baby spinach",
              "Spanish onions",
              "Flour tortillas",
              "Shredded pepper jack cheese",
              "Medium tomato salsa",
              "Cilantro",
              "Extra virgin olive oil",
              "Lime juice",
              "Jalapeno peppers",
              "Garlic",
              "Kosher salt",
              "Garlic powder",
              "Ground black pepper",
              "Marjoram leaves",
              "Onion powder",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 7908508,
            "meal": "Lunch",
            "name": "Spinach and Cheese Flauta",
            "nutrition": {
              "calories": "204 cal",
              "carbohydrates": "21.8 g",
              "cholesterol": "16 mg",
              "fat": "9.7 g",
              "fiber": "2.9 g",
              "iron": "2.4 mg",
              "protein": "8.5 g",
              "saturatedFat": "4.0 g",
              "servingSize": "1 Each",
              "sugar": "2.4 g",
              "vitaminA": "4181.9 IU",
              "vitaminC": "15.3 mg",
            },
          },
          {
            "allergens": [
              "Soy",
            ],
            "hasInfo": true,
            "ingredients": [
              "Low-sodium vegetable stock",
              "Plum tomatoes",
              "Corn",
              "Onions",
              "Dried celery",
              "Ground cori",
              "Er",
              "Kosher salt",
              "Garlic",
              "Canola oil",
              "Ground black pepper",
              "Dried thyme",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5676883,
            "meal": "Lunch",
            "name": "Roasted Corn and Tomato Soup",
            "nutrition": {
              "calories": "70 cal",
              "carbohydrates": "13.7 g",
              "cholesterol": "0 mg",
              "fat": "1.6 g",
              "fiber": "2.4 g",
              "iron": "0.5 mg",
              "protein": "2.7 g",
              "saturatedFat": "0.1 g",
              "servingSize": "6 Fluid Ounce",
              "sugar": "4.5 g",
              "vitaminA": "1378.9 IU",
              "vitaminC": "11.9 mg",
            },
          },
          {
            "allergens": [
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Low-sodium chicken stock",
              "Sub matzo ball",
              "Chicken thighs",
              "Onions",
              "Carrots",
              "Dried celery",
              "Fresh dill",
              "Black peppercorns",
              "Fresh bay leaves",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 3617831,
            "meal": "Lunch",
            "name": "Matzo Ball Soup",
            "nutrition": {
              "calories": "98 cal",
              "carbohydrates": "7.8 g",
              "cholesterol": "61 mg",
              "fat": "6.3 g",
              "fiber": "0.3 g",
              "iron": "0.2 mg",
              "protein": "2.7 g",
              "saturatedFat": "3.4 g",
              "servingSize": "6 Fluid Ounce",
              "sugar": "0.7 g",
              "vitaminA": "199.7 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Green garbanzo beans",
              "Avocado-lime vinaigrette",
              "Apples",
              "Crispy chickpeas",
              "Cilantro",
              "Carrots",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 3362345,
            "meal": "Lunch",
            "name": "Fresh Green Garbanzo Salad with Apples, Avocado-Lime Vinaigrette, and Crispy Chickpeas",
            "nutrition": {
              "calories": "131 cal",
              "carbohydrates": "12.0 g",
              "cholesterol": "0 mg",
              "fat": "7.6 g",
              "fiber": "3.2 g",
              "iron": "1.1 mg",
              "protein": "3.6 g",
              "saturatedFat": "1.0 g",
              "servingSize": "3 Ounce",
              "sugar": "2.0 g",
              "vitaminA": "541.3 IU",
              "vitaminC": "16.2 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
            ],
            "hasInfo": true,
            "ingredients": [
              "Wild baby arugula",
              "Cannellini beans",
              "Feta cheese",
              "Tomatoes",
              "Cucumber",
              "Kalamata olives",
              "Red onions",
              "Extra virgin olive oil",
              "Pepperoncini peppers",
              "Lemon juice",
              "Red wine vinegar",
              "Parsley",
              "Mint",
              "Garlic",
              "Curly parsley",
              "Oregano",
              "Kosher salt",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 3871561,
            "meal": "Lunch",
            "name": "Greek Salad with Arugula",
            "nutrition": {
              "calories": "72 cal",
              "carbohydrates": "4.6 g",
              "cholesterol": "7 mg",
              "fat": "5.0 g",
              "fiber": "1.4 g",
              "iron": "0.9 mg",
              "protein": "3.3 g",
              "saturatedFat": "1.6 g",
              "servingSize": "3 Ounce",
              "sugar": "1.5 g",
              "vitaminA": "1113.7 IU",
              "vitaminC": "8.7 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Quinoa",
              "Low-sodium black beans",
              "Bell peppers",
              "Corn kernels",
              "Scallions",
              "Extra virgin olive oil",
              "Lime juice",
              "Cilantro",
              "Kosher salt",
              "Ground cumin",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5348503,
            "meal": "Lunch",
            "name": "Southwest Quinoa Salad",
            "nutrition": {
              "calories": "105 cal",
              "carbohydrates": "15.8 g",
              "cholesterol": "0 mg",
              "fat": "3.8 g",
              "fiber": "1.8 g",
              "iron": "0.9 mg",
              "protein": "3.0 g",
              "saturatedFat": "0.4 g",
              "servingSize": "3 Ounce",
              "sugar": "1.5 g",
              "vitaminA": "136.7 IU",
              "vitaminC": "19.6 mg",
            },
          },
          {
            "allergens": [
              "Nuts",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Pea protein",
              "Canola oil",
              "Refined coconut oil",
              "Water",
              "Yeast extract",
              "Maltodextrin",
              "Natural flavors",
              "Gum arabic",
              "Sunflower oil",
              "Salt",
              "Succinic acid",
              "Acetic acid",
              "Non-gmo modified food starch",
              "Cellulose from bamboo",
              "Methylcellulose",
              "Potato starch",
              "Beet juice extract",
              "Ascorbi",
              "Wheat hamburger bun",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 6784067,
            "meal": "Lunch",
            "name": "Beyond Meat Burger",
            "nutrition": {
              "calories": "438 cal",
              "carbohydrates": "33.9 g",
              "cholesterol": "0 mg",
              "fat": "23.9 g",
              "fiber": "5.0 g",
              "iron": "1.4 mg",
              "protein": "25.9 g",
              "saturatedFat": "8.5 g",
              "servingSize": "1 Each",
              "sugar": "3.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "53.9 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Grass-fed ground beef",
              "Mushroom duxelles",
              "Kosher salt",
              "Black pepper",
              "Brioche roll",
              "Better burger leaf lettuce",
              "Tomato",
              "Vegan mayo",
              "Lemon juice",
              "Dill pickle relish",
              "Garlic powder",
              "Paprika",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5263541,
            "meal": "Lunch",
            "name": "Grass-Fed Hand Shaped Burger",
            "nutrition": {
              "calories": "397 cal",
              "carbohydrates": "29.2 g",
              "cholesterol": "85 mg",
              "fat": "21.5 g",
              "fiber": "2.1 g",
              "iron": "2.2 mg",
              "protein": "20.8 g",
              "saturatedFat": "9.1 g",
              "servingSize": "1 Sandwich",
              "sugar": "3.5 g",
              "vitaminA": "2219.9 IU",
              "vitaminC": "8.1 mg",
            },
          },
          {
            "allergens": [
              "Dairy",
              "Eggs",
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Grass-fed ground beef",
              "Mushroom duxelles",
              "Kosher salt",
              "Black pepper",
              "Brioche roll",
              "Better burger leaf lettuce",
              "Tomatoes",
              "White cheddar cheese",
              "Vegan mayo",
              "Lemon juice",
              "Dill pickle relish",
              "Garlic powder",
              "Paprika",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5416409,
            "meal": "Lunch",
            "name": "Grass-Fed Hand-Shaped Cheeseburger",
            "nutrition": {
              "calories": "452 cal",
              "carbohydrates": "29.7 g",
              "cholesterol": "103 mg",
              "fat": "26.5 g",
              "fiber": "2.1 g",
              "iron": "2.2 mg",
              "protein": "24.4 g",
              "saturatedFat": "12.1 g",
              "servingSize": "1 Sandwich",
              "sugar": "3.5 g",
              "vitaminA": "2370.1 IU",
              "vitaminC": "8.1 mg",
            },
          },
          {
            "allergens": [
              "Soy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Vegan black bean",
              "Sweet potato burger",
              "Wheat hamburger bun",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5926612,
            "meal": "Lunch",
            "name": "Vegan Sweet Potato and Black Bean Burger",
            "nutrition": {
              "calories": "239 cal",
              "carbohydrates": "43.0 g",
              "cholesterol": "0 mg",
              "fat": "3.5 g",
              "fiber": "5.0 g",
              "iron": "3.2 mg",
              "protein": "11.0 g",
              "saturatedFat": "0.5 g",
              "servingSize": "1 Each",
              "sugar": "5.0 g",
              "vitaminA": "1748.9 IU",
              "vitaminC": "6.0 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Tomatoes",
              "Suntan bell pepper",
              "Basmati rice",
              "Medium tomato salsa",
              "Onions",
              "Canola oil",
              "Garlic puree",
              "Ground cori",
              "Er",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 5076605,
            "meal": "Lunch",
            "name": "Mexican Rice",
            "nutrition": {
              "calories": "127 cal",
              "carbohydrates": "25.5 g",
              "cholesterol": "0 mg",
              "fat": "1.8 g",
              "fiber": "1.4 g",
              "iron": "0.1 mg",
              "protein": "3.1 g",
              "saturatedFat": "0.1 g",
              "servingSize": "4 Ounce",
              "sugar": "2.9 g",
              "vitaminA": "223.4 IU",
              "vitaminC": "26.9 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Brussels sprouts",
              "Green squash",
              "Red bell peppers",
              "Extra virgin olive oil",
              "Italian parsley",
              "Red wine vinegar",
              "Kosher salt",
              "Basil",
              "Ground black pepper",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 6072636,
            "meal": "Lunch",
            "name": "Roasted Brussels Sprouts with Squash and Red Peppers",
            "nutrition": {
              "calories": "74 cal",
              "carbohydrates": "7.2 g",
              "cholesterol": "0 mg",
              "fat": "4.9 g",
              "fiber": "2.8 g",
              "iron": "1.1 mg",
              "protein": "2.4 g",
              "saturatedFat": "0.7 g",
              "servingSize": "4 Ounce",
              "sugar": "2.8 g",
              "vitaminA": "1444.8 IU",
              "vitaminC": "79.6 mg",
            },
          },
          {
            "allergens": [],
            "hasInfo": true,
            "ingredients": [
              "Long-grain brown rice",
              "Tap water",
            ],
            "isGlutenFree": false,
            "isVegan": true,
            "isVegetarian": true,
            "itemID": 4166320,
            "meal": "Lunch",
            "name": "Steamed Brown Rice",
            "nutrition": {
              "calories": "231 cal",
              "carbohydrates": "49.4 g",
              "cholesterol": "0 mg",
              "fat": "1.5 g",
              "fiber": "1.5 g",
              "iron": "0.6 mg",
              "protein": "4.6 g",
              "saturatedFat": "0.0 g",
              "servingSize": "4 Ounce",
              "sugar": "0.0 g",
              "vitaminA": "0.0 IU",
              "vitaminC": "0.0 mg",
            },
          },
          {
            "allergens": [
              "Alcohol",
              "Nuts",
              "Dairy",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "Pastry flour",
              "Unsalted butter",
              "Confectioners sugar",
              "Macadamia nuts",
              "Shredded sweetened coconut",
              "Passion fruit puree",
              "Pure vanilla extract",
              "Salt",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": false,
            "itemID": 5480238,
            "meal": "Lunch",
            "name": "Passion Fruit Coconut Macadamia Shortbread",
            "nutrition": {
              "calories": "256 cal",
              "carbohydrates": "23.0 g",
              "cholesterol": "36 mg",
              "fat": "18.0 g",
              "fiber": "1.3 g",
              "iron": "0.5 mg",
              "protein": "2.3 g",
              "saturatedFat": "10.0 g",
              "servingSize": "1 Cookie",
              "sugar": "6.2 g",
              "vitaminA": "419.6 IU",
              "vitaminC": "0.1 mg",
            },
          },
          {
            "allergens": [
              "Alcohol",
              "Dairy",
              "Eggs",
              "Wheat",
              "Gluten",
            ],
            "hasInfo": true,
            "ingredients": [
              "All-purpose flour",
              "Unsalted butter",
              "Semisweet chocolate chip",
              "Light brown sugar",
              "Superfine sugar",
              "Eggs",
              "Pure vanilla extract",
              "Salt",
              "Cream of tartar",
              "Baking soda",
            ],
            "isGlutenFree": false,
            "isVegan": false,
            "isVegetarian": true,
            "itemID": 4118782,
            "meal": "Lunch",
            "name": "Chocolate Chip Blondies",
            "nutrition": {
              "calories": "278 cal",
              "carbohydrates": "39.4 g",
              "cholesterol": "47 mg",
              "fat": "12.7 g",
              "fiber": "1.2 g",
              "iron": "1.5 mg",
              "protein": "3.2 g",
              "saturatedFat": "7.7 g",
              "servingSize": "1 Serving",
              "sugar": "23.4 g",
              "vitaminA": "298.6 IU",
              "vitaminC": "0.0 mg",
            },
          },
        ],
      },
    }