/* Expected Inputs */
export const locationColumns = [
    "ID_LOCATION",
    "LOCATIONCODE",
    "DININGLOCATIONNAME",
    "TYPE",
    "CAPACITY",
    "GEOLOCATION",
    "ISCLOSED",
    "ADDRESS",
    "PHONE",
    "MANAGER1NAME",
    "MANAGER1EMAIL",
    "MANAGER2NAME",
    "MANAGER2EMAIL",
    "MANAGER3NAME",
    "MANAGER3EMAIL",
    "MANAGER4NAME",
    "MANAGER4EMAIL"
];

export const locationData = [
    [
        1,
        2,
        "Berkeley",
        "Residential",
        0,
        "41.310131,-72.928222",
        1,
        "205 Elm Street, New Haven, CT 06511",
        "(203) 432-0423",
        "David Brooks",
        "d.brooks@yale.edu",
        "Paul Tinker",
        "Paul.Tinker@yale.edu",
        "Kristin Elliot",
        "kristin.elliot@yale.edu",
        null,
        null
    ],
    [
        2,
        3,
        "Branford",
        "Residential",
        0,
        "41.310054,-72.930261",
        1,
        "74 High Street, New Haven, CT 06511",
        "(203) 432-7995",
        "Maureen ODonnell-Young",
        "Maureen.odonnell@yale.edu",
        "Christopher Molyneux",
        "christopher.molyneux@yale.edu",
        "Ellen Habelow",
        "Ellen.Habelow@yale.edu",
        "Greg Ward",
        "gregory.ward@yale.edu"
    ],
    [
        4,
        5,
        "Davenport",
        "Residential",
        0,
        "41.310086,-72.931194",
        1,
        "248 York Street, New Haven, CT 06511",
        "(203) 432-0432",
        "Deanna Tucciarone",
        "Deanna.tucciarone@yale.edu",
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        28,
        23,
        "Franklin",
        "Residential",
        0,
        "41.314381,-72.925160",
        1,
        "88 Prospect St, New Haven, CT, 06511",
        "(203) 432-3106",
        "Chase Sobelman",
        "chase.sobelman@yale.edu",
        "Megan Roberts",
        "megan.roberts@yale.edu",
        "Brett Rappaport",
        "brett.rappaport@yale.edu",
        "Jeff Hardy",
        "Jeffrey.Hardy@yale.edu"
    ],
    [
        3,
        4,
        "Grace Hopper",
        "Residential",
        0,
        "41.309833,-72.927525",
        1,
        "189 Elm Street, New Haven, CT 06511",
        "(203) 432-0425",
        "Gina Gentile",
        "gina.gentile@yale.edu",
        "Elissa Jacknick",
        "elissa.jacknick@yale.edu",
        null,
        null,
        null,
        null
    ],
    [
        6,
        6,
        "Jonathan Edwards",
        "Residential",
        0,
        "41.308745,-72.930081",
        1,
        "68 High Street, New Haven, CT 06511",
        "(203) 432-0438",
        "May Cabahug",
        "mary.cabahug@yale.edu",
        "Rashmi Nath",
        "rashmi.nath@yale.edu",
        null,
        null,
        null,
        null
    ],
    [
        5,
        1,
        "Morse",
        "Residential",
        0,
        "41.312532,-72.930352",
        1,
        "302 York Street, New Haven, CT 06511",
        "(203) 432-0443",
        "Christina Wethington",
        "christine.wethington@yale.edu",
        "Danielle Lucci",
        "danielle.lucci@yale.edu",
        "Kristin Butler",
        "kristen.butler@yale.edu",
        null,
        null
    ],
    [
        29,
        24,
        "Pauli Murray",
        "Residential",
        0,
        "41.314699,-72.925416",
        1,
        "6 Prospect Place, New Haven, CT, 06511",
        "(203) 432-3106",
        "Chase Sobelman",
        "chase.sobelman@yale.edu",
        "Megan Roberts",
        "megan.roberts@yale.edu",
        "Brett Rappaport",
        "brett.rappaport@yale.edu",
        "Jeff Hardy",
        "Jeffrey.Hardy@yale.edu"
    ],
    [
        7,
        7,
        "Pierson",
        "Residential",
        3,
        "41.310292,-72.932278",
        0,
        "231 Park Street, New Haven, CT 06511",
        "(203) 432-0434",
        "Kory Evasick",
        "kory.evasick@yale.edu",
        "Catherine McCue",
        "catherine.mccue@yale.edu",
        null,
        null,
        null,
        null
    ],
    [
        23,
        3,
        "Saybrook",
        "Residential",
        0,
        "41.310022,-72.929794",
        1,
        "242 Elm Street, New Haven, CT 06511",
        "(203) 432-7995",
        "Maureen ODonnell-Young",
        "Maureen.odonnell@yale.edu",
        "Christopher Molyneux",
        "christopher.molyneux@yale.edu",
        "Ellen Habelow",
        "Ellen.Habelow@yale.edu",
        "Greg Ward",
        "gregory.ward@yale.edu"
    ],
    [
        8,
        8,
        "Silliman",
        "Residential",
        0,
        "41.311138,-72.925165",
        1,
        "505 College Street, New Haven, CT 06511",
        "(203) 432-0440",
        "Jennifer Currier",
        "jennifer.currier@yale.edu",
        "James Murray",
        "james.murray@yale.edu",
        null,
        null,
        null,
        null
    ],
    [
        24,
        1,
        "Stiles",
        "Residential",
        7,
        "41.312492,-72.930647",
        0,
        "304 York Street, New Haven, CT 06511",
        "(203) 432-0443",
        "Christina Wethington",
        "christine.wethington@yale.edu",
        "Danielle Lucci",
        "danielle.lucci@yale.edu",
        "Kristin Butler",
        "kristen.butler@yale.edu",
        null,
        null
    ],
    [
        9,
        9,
        "Timothy Dwight",
        "Residential",
        0,
        "41.310002,-72.923791",
        1,
        "345 Temple Street, New Haven, CT 06511",
        "(203) 432-0436",
        "Sammy Feliciano",
        "samuel.feliciano@yale.edu",
        "Matthew Beard",
        "matthew.beard@yale.edu",
        null,
        null,
        null,
        null
    ],
    [
        10,
        10,
        "Trumbull",
        "Residential",
        0,
        "41.31059,-72.929236",
        1,
        "241 Elm Street, New Haven, CT 06511",
        "(203) 432-0444",
        "Yasser Ezzelden",
        "yasser.ezzelden@yale.edu",
        "Bernadette Janis",
        "Bernadette.janis@yale.edu",
        null,
        null,
        null,
        null
    ],
    [
        25,
        22,
        "Becton Café",
        "Retail",
        null,
        "41.312398,-72.925322",
        1,
        "15 Prospect St, New Haven, CT 06511",
        "(203) 432-1827",
        "Chelsey Toong",
        "chelsey.toong@yale.edu",
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        15,
        17,
        "Café Med",
        "Retail",
        null,
        "41.304497,-72.934177",
        1,
        "367 Cedar Street New Haven, CT 06510",
        "(203) 785-5875",
        "Bettyejo Mackiewicz",
        "Bettyejo.Mackiewicz@yale.edu",
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        27,
        100,
        "Charley's Place (SOM)",
        "Retail",
        null,
        "41.315132,-72.9224197",
        1,
        "Edward P. Evans Hall at 165 Whitney Avenue, New Haven",
        "(203) 436-9933",
        "William Allison",
        "william.allison@yale.edu",
        "Julie Carrion",
        "julie.carrion@yale.edu",
        null,
        null,
        null,
        null
    ],
    [
        14,
        13,
        "Divinity School Refectory",
        "Retail",
        null,
        "41.323588,-72.92134",
        1,
        "409 Prospect Street, New Haven, CT 06511",
        "(203) 432-3407",
        "Donna Hall",
        "donna.hall@yale.edu",
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        19,
        16,
        "Durfees",
        "Retail",
        null,
        "41.309615,-72.928061",
        1,
        "200 Elm Street, New Haven, CT 06511",
        "(203) 432-0451",
        "Lynn Torello",
        "lynn.torello@yale.edu",
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        26,
        21,
        "HC Café",
        "Retail",
        null,
        "41.315473,-72.928058",
        1,
        "55 Lock Street, New Haven, CT 06511",
        "(203) 436-5731",
        "Bettyejo Mackiewicz",
        "Bettyejo.Mackiewicz@yale.edu",
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        16,
        15,
        "KBT Café",
        "Retail",
        null,
        "41.317025,-72.922681",
        1,
        "Kline Biology Tower, New Haven, CT 06511",
        "(203) 432-3402",
        "Bettyejo Mackiewicz",
        "Bettyejo.Mackiewicz@yale.edu",
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        30,
        72,
        "Slifka Center",
        "Retail",
        null,
        "41.310255, -72.925125",
        0,
        "80 Wall St, New Haven, CT 06511",
        "(203) 432-1890",
        "Rick Terry",
        "slifka@lessings.com",
        "Ziv Eisenberg",
        "ziv.eisenberg@yale.edu",
        null,
        null,
        null,
        null
    ],
    [
        18,
        19,
        "Thain Family Café",
        "Retail",
        null,
        "41.310566,-72.927412",
        1,
        "Bass Library, 130 Wall Street, New Haven, CT 06511",
        "(203) 436-4170",
        "Lynn Torello",
        "lynn.torello@yale.edu",
        null,
        null,
        null,
        null,
        null,
        null
    ],
    [
        22,
        18,
        "West Campus",
        "Retail",
        null,
        "41.258388,-72.989237",
        0,
        "141 Frontage Road, West Haven, CT",
        "(203) 432-3407",
        "Donna Hall",
        "donna.hall@yale.edu",
        null,
        null,
        null,
        null,
        null,
        null
    ]
];

export const locationResponse = {
    COLUMNS: locationColumns,
    DATA: locationData
};

export const mealColumns = [
    "ID_LOCATION",
    "LOCATIONCODE",
    "LOCATION",
    "MEALNAME",
    "MEALCODE",
    "MENUDATE",
    "ID",
    "COURSE",
    "COURSECODE",
    "MENUITEMID",
    "MENUITEM",
    "ISPAR",
    "MEALOPENS",
    "MEALCLOSES",
    "ISDEFAULTMEAL",
    "ISMENU"
];

export const hotBreakfastDataToday = [
    5,
    1,
    "Morse",
    "Hot Breakfast",
    2,
    "March, 1 2019 00:00:00",
    1.3818222e7,
    "The Grill",
    23.0,
    4822535.0,
    "Multigrain Pancakes",
    true,
    "07:30 AM",
    "10:30 AM",
    1,
    true
];
export const hotBreakfastDataTomorrow = [
    5,
    1,
    "Morse",
    "Hot Breakfast",
    2,
    "March, 2 2019 00:00:00",
    1.3899688e7,
    "Entrees",
    13.0,
    5908402.0,
    "Vegan Waffles",
    false,
    "07:30 AM",
    "10:30 AM",
    1,
    true
];
export const lunchData = [
    5,
    1,
    "Morse",
    "Lunch",
    4,
    "March, 1 2019 00:00:00",
    1.3818451e7,
    "The Salad",
    15.0,
    4883833.0,
    "Farro Salad with Raisins",
    true,
    "11:30 AM",
    "01:30 PM",
    0,
    true
];
export const dinnerData = [
    5,
    1,
    "Morse",
    "Dinner",
    5,
    "March, 1 2019 00:00:00",
    1.3818499e7,
    "Entrees",
    13.0,
    3579035.0,
    "Naples Style Beef Chuck",
    false,
    "05:00 PM",
    "07:00 PM",
    0,
    true
];

export const singleMenuData = [
    hotBreakfastDataToday,
    hotBreakfastDataTomorrow,
    lunchData,
    dinnerData
];

export const singleMenu = { COLUMNS: mealColumns, DATA: singleMenuData };

export const emptyMenu = { COLUMNS: mealColumns, DATA: [] };

/* Expected Responses */

export const singleLocationToday = {
    contBreakfast: undefined,
    hotBreakfast: {
        openingTime: "07:30 AM",
        closingTime: "10:30 AM",
        transferTime: undefined
    },
    brunch: undefined,
    lunch: {
        openingTime: "11:30 AM",
        closingTime: "01:30 PM",
        transferTime: undefined
    },
    dinner: {
        openingTime: "05:00 PM",
        closingTime: "07:00 PM",
        transferTime: undefined
        // TODO: Hardcode in transfer times in ../../config/DiningHallHours
        // transferTime: "06:00 PM"
    }
};

export const singleLocationTomorrow = {
    contBreakfast: undefined,
    hotBreakfast: {
        openingTime: "07:30 AM",
        closingTime: "10:30 AM",
        transferTime: undefined
    },
    brunch: undefined,
    lunch: undefined,
    dinner: undefined
};

export const morseExpectedResponse = {
    name: "Morse",
    todayHours: singleLocationToday,
    tomorrowHours: singleLocationTomorrow,
    isOpen: false,
    busyness: 0,
    geolocation: [41.312532, -72.930352]
};

export const stilesExpectedResponse = {
    name: "Stiles",
    todayHours: singleLocationToday,
    tomorrowHours: singleLocationTomorrow,
    isOpen: true,
    busyness: 7,
    geolocation: [41.312492, -72.930647]
};

export const morseExpectedResponseEmpty = {
    name: "Morse",
    todayHours: undefined,
    tomorrowHours: undefined,
    isOpen: false,
    busyness: 0,
    geolocation: [41.312532, -72.930352]
};

export const allLocationsExpectedResponse = {
    Morse: morseExpectedResponse,
    Stiles: stilesExpectedResponse
};
