export const GET_ALL_DINING_HALLS_INFORMATION_REQUEST = "GET_ALL_DINING_HALLS_INFORMATION_REQUEST";
export const GET_ALL_DINING_HALLS_INFORMATION_SUCCESS = "GET_ALL_DINING_HALLS_INFORMATION_SUCCESS";
export const GET_ALL_DINING_HALLS_INFORMATION_FAILURE = "GET_ALL_DINING_HALLS_INFORMATION_FAILURE";

export const GET_MENU_INFORMATION_REQUEST = "GET_MENU_INFORMATION_REQUEST";
export const GET_MENU_INFORMATION_SUCCESS = "GET_MENU_INFORMATION_SUCCESS";
export const GET_MENU_INFORMATION_FAILURE = "GET_MENU_INFORMATION_FAILURE";

export const GET_MENU_ITEM_INFORMATION_REQUEST = "GET_MENU_ITEM_INFORMATION_REQUEST";
export const GET_MENU_ITEM_INFORMATION_SUCCESS = "GET_MENU_ITEM_INFORMATION_SUCCESS";
export const GET_MENU_ITEM_INFORMATION_FAILURE = "GET_MENU_ITEM_INFORMATION_FAILURE";

export const GET_FILTERS_REQUEST = "GET_FILTERS_REQUEST";
export const GET_FILTERS_SUCCESS = "GET_FILTERS_SUCCESS";
export const GET_FILTERS_FAILURE = "GET_FILTERS_FAILURE";
export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";

export const GET_FAVORITES_REQUEST = "GET_FAVORITES_REQUEST";
export const GET_FAVORITES_SUCCESS = "GET_FAVORITES_SUCCESS";
export const GET_FAVORITES_FAILURE = "GET_FAVORITES_FAILURE";
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";

export const SAVE_USER_NOTIFICATION_ID = "SAVE_USER_NOTIFICATION_ID";
